CentaurusInfra/arktos

- pkg/kubectl/cmd/create/create.go
- pkg/kubectl/cmd/create/multi_tenancy_create_test.go
Make kubectl-create support multi-tenancy. Fix issue https://github.com/futurewei-cloud/arktos/issues/7
Here is the test output from my dev box:
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh create -f ~/test/tenant.yaml 
tenant/scale-tenent3 created
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh create namespace test-ns --tenant scale-tenent2
namespace/test-ns created
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh get namespaces --all-tenants 
TENANT          NAME              STATUS   AGE     TENANT
default         default           Active   4m48s   default
default         kube-node-lease   Active   4m53s   default
default         kube-public       Active   4m53s   default
default         kube-system …
> multi-tenancy kubectl-create

- docs/OWNERS
Changes:
1.  To easy sharing with external teams, add the Kubecon 2019 NA booth demo slides into folder \docs\slides.   The code name in the slides has been changed from "Alkaid" to "Arktos".
2.  Update the doc owners file (sorted alphabetically) based on the owners file under root folder.
> Add Kubecon 2019 NA booth demo slides and update owners file

- pkg/controller/serviceaccount/serviceaccounts_controller.go
- pkg/controller/serviceaccount/serviceaccounts_controller_test.go
- pkg/controller/serviceaccount/tokengetter.go
- pkg/controller/serviceaccount/tokens_controller.go
- pkg/controller/serviceaccount/tokens_controller_test.go
- pkg/controller/volume/attachdetach/attach_detach_controller.go
- pkg/controller/volume/expand/expand_controller.go
- pkg/controller/volume/persistentvolume/volume_host.go
- pkg/kubelet/configmap/configmap_manager.go
- pkg/kubelet/configmap/configmap_manager_test.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/secret/fake_manager.go
- pkg/kubelet/secret/secret_manager.go
- pkg/kubelet/secret/secret_manager_test.go
- pkg/kubelet/util/manager/cache_based_manager.go
- pkg/kubelet/util/manager/cache_based_manager_test.go
- pkg/kubelet/util/manager/manager.go
- pkg/kubelet/util/manager/watch_based_manager.go
- pkg/kubelet/util/manager/watch_based_manager_test.go
- pkg/kubelet/volume_host.go
- pkg/volume/plugins.go
- pkg/volume/projected/projected.go
- pkg/volume/projected/projected_test.go
- pkg/volume/secret/secret.go
- pkg/volume/secret/secret_test.go
- pkg/volume/testing/testing.go
- test/integration/kubelet/watch_manager_test.go
- test/integration/serviceaccount/service_account_test.go
This PR fixed the issue reported in https://github.com/futurewei-cloud/arktos/issues/8.
The chnages made are:
1. Make service account controller support multi-tenancy
2. Make token controller support multi-tenancy
3. Make the process to get secret in service account support multi-tenancy
> Qchen/multi tenancy/fix deployment creation

- pkg/kubectl/cmd/create/BUILD
Fix: add the newly added test file to the BUILD, so it will be picked up by the bazel test.
> fix kubectl create bazel BUILD file

- cmd/kube-scheduler/app/options/deprecated.go
- cmd/kube-scheduler/app/options/options_test.go
- cmd/kubelet/app/options/options.go
- cmd/kubelet/app/options/options_test.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
- test/integration/apiserver/apiserver_partition_test.go
There is an issue with WithFromKey which converts key to 0x00. In that case the watchers with that option pick up all the events. 
Using GetPrefixRangeEnd to get the least biggest string of the existing key instead to fix the issue
> Fixed the unbounded watcher range bug

- pkg/kubectl/cmd/create/BUILD
- pkg/kubectl/cmd/create/create.go
- pkg/kubectl/cmd/create/create_namespace.go
- pkg/kubectl/cmd/create/create_tenant.go
- pkg/kubectl/generate/versioned/BUILD
- pkg/kubectl/generate/versioned/generator.go
- pkg/kubectl/generate/versioned/tenant.go
- pkg/kubectl/generate/versioned/tenant_test.go
This PR adds a kubectl subcommand. "kubectl create tenant". So users now create a tenant using command "kubectl create tenant [tenant_name]", instead of having to create a yaml file and run "kubectl create -f [tenant.yaml]".
test output: 
qianchen@qianchen-VirtualBox: ~/gopath/chenqian/arktos$ cluster/kubectl.sh create tenant sample-test-tenant
tenant/sample-test-tenant created
qianchen@qianchen-VirtualBox: ~/gopath/chenqian/arktos$ cluster/kubectl.sh get tenants
NAME                 STATUS   AGE
sample-test-tenant   Active   2s
> add subcommnand kubectl-create-tenant

- pkg/kubectl/cmd/apiresources/apiresources.go
This is part of the work to make api-resource discovery support multi-tenancy. With this change, the output of "kubectl api-resources" will include the info whether the resource is "tenanted".
Test output:
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh api-resources
NAME                              SHORTNAMES   APIGROUP                       TENANTED   NAMESPACED   KIND
actions                           ac                                          true       true         Action
bindings                                                                      true       true         Binding
componentstatuses                 cs                                          false      false        ComponentStatus
configmaps                        cm …
> show resource tenanted info in command kubectl api-resources

- staging/src/k8s.io/apiserver/pkg/endpoints/filters/BUILD
- staging/src/k8s.io/apiserver/pkg/endpoints/filters/tenantInfo.go
- staging/src/k8s.io/apiserver/pkg/server/config.go
Test result in local dev box:
(I created a context named "local" where the tenant of the user is "qian")
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh --context=local create ns qc-test
namespace/qc-test created
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh get namespaces --tenant qian
NAME      STATUS   AGE     TENANT
qc-test   Active   2m51s   qian
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh --context=local create ns qc-test --tenant another_tenant
Error from server (InternalError): an error on the server ("Internal Server Error: \"/api/v1/tenants/another_tenant/namespaces\": User under tenant qian is not allowed to access object under tenant another_tenant.") has prevented the request from succeeding
> set the tenant info in Object per user info

- hack/lib/util.sh
- pkg/apis/authentication/v1/zz_generated.conversion.go
- pkg/apis/authentication/v1beta1/zz_generated.conversion.go
- staging/src/k8s.io/api/authentication/v1/generated.proto
- staging/src/k8s.io/api/authentication/v1beta1/generated.proto
- staging/src/k8s.io/apiserver/pkg/audit/event/attributes.go
- staging/src/k8s.io/apiserver/pkg/authentication/group/authenticated_group_adder.go
- staging/src/k8s.io/apiserver/pkg/authentication/request/anonymous/anonymous.go
- staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go
- staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
- staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go
- staging/src/k8s.io/apiserver/pkg/endpoints/filters/authorization.go
- test/integration/apiserver/apiserver_partition_test.go
- test/integration/auth/rbac_test.go
The format of the cert is changed to using /O (organization) for tenant and /OU (organization unit) for groups. Changed arktos-up.sh to create cert in this format.
added extraction of tenant from x509. after authentication, tenant info is available in requestAttributes.GetUser()
> extract tenant from x509 cert

- docs/design-proposals/multi-tenancy/multi-tenancy-overview.md
Fix two url errors in a design document. The previous one missed a part "multi-tenancy" in its absolute URL. Also switch to relative URL for easy maintenance.
> A quick fix for image urls in design document

- pkg/cloudfabric-controller/client_builder.go
Tokens are missed when they are verified and returned.
> Fixed the connection issue of the controller manager crash

- pkg/controller/apis/config/v1alpha1/doc.go
- pkg/kubelet/kuberuntime/kuberuntime_manager.go
Fixed make update issue that caused the following error:
pkg/controller/apis/config/v1alpha1/zz_generated.conversion.go:351:12: undefined: Convert_v1alpha1_TenantControllerConfiguration_To_config_TenantControllerConfiguration
pkg/controller/apis/config/v1alpha1/zz_generated.conversion.go:429:12: undefined: Convert_config_TenantControllerConfiguration_To_v1alpha1_TenantControllerConfiguration
make update completed successfully on my test box
```bash
Running update-bazel
Running update-gofmt
Running copyright check for repo: /root/code/src/k8s.io/arktos, logging to /root/code/src/k8s.io/arktos/_output/ArktosCopyrightTool.log
~/code/src/k8s.io/arktos ~/code/src/k8s.io/arktos
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your …
```
> fix make upadte issue with zz_generated.conversion.go

- hack/testdata/auth-tokens.csv
- staging/src/k8s.io/apiserver/pkg/authentication/token/tokenfile/BUILD
- staging/src/k8s.io/apiserver/pkg/authentication/token/tokenfile/tokenfile.go
- staging/src/k8s.io/apiserver/pkg/authentication/token/tokenfile/tokenfile_test.go
Issue https://github.com/futurewei-cloud/arktos/issues/38
This change extracts tenant from token (csv) file. 
The empty entry till the end indicates the new format that is followed by the tenant. Without the empty entry, it falls back to the old format while setting tenant to "system" internally.
Most are auto-gen files. The real change is in staging/src/k8s.io/apiserver/pkg/authentication/token/tokenfile/tokenfile.go
Old format:
```bash
[token],[user],[uid],[groups...],[other data]
```
New format:
```bash
[token],[user],[uid],[groups...],[other data],,[tenant]
```
To enable:
add the following to apiserver startup option
```bash
--token-auth-file=/path/to/tokenfile
```
For example, with the following csv file:
```bash
abc,pengdu,pengduuid,"admin",,tenant
```
Set the context with 
```bash …
```
> extract tenant from bearer token file

- staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_discovery_controller.go
- staging/src/k8s.io/apiserver/pkg/endpoints/discovery/BUILD
- staging/src/k8s.io/apiserver/pkg/endpoints/discovery/version.go
- staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go
Display different resource types for system-tenant user and regular tenant user.
Test output:
When the context is for a regular-tenant user ( only tenant-scope resources are shown)
qianchen@qianchen-VirtualBox:~/gopath/chenqian/arktos$ cluster/kubectl.sh --context=local api-resources
NAME                         SHORTNAMES   APIGROUP                    TENANTED   NAMESPACED   KIND
actions                      ac                                       true       true         Action
bindings                                                              true       true         Binding
configmaps                   cm                                       true       true         ConfigMap
endpoints                    ep                                       true       true         Endpoints …
> multi-tenancy resource discovery

- pkg/master/reconcilers/mastercount.go
- staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile/BUILD
- staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile/passwordfile.go
- staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile/passwordfile_test.go
Part 3 of https://github.com/futurewei-cloud/arktos/issues/38
Here's [how static password file works](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-password-file)
The file format is extended with tenant similar to what's done to the token auth file.
Old format:
```bash
[password],[user],[uid],[groups...],[other data]
```
New format:
```bash
[password],[user],[uid],[groups...],[other data],,[tenant]
```
The empty entry till the end indicates it is the new format. Without the empty entry, it falls back to the old format while setting tenant to "system" internally, hence backward compatible. 
Once the username and password is verified correctly, user info is returned now with their tenant from the static file.
> add tenant extraction from basic auth token file

- hack/arktos-up.sh
This change allows a cluster started by arktos-up.sh to be access from other host through its public ip address (for example, in an AWS instance).
If a public ip address is defined using environment variable PUBLIC_IP,  this ip will be added to the generated apiserver cert as an additional host, and to admin.kubeconfig as the server ip. If the env variable is not defined, it works the same way as before.
Tested by starting up a cluster using arktos-up.sh with and without PUBLIC_IP defined on the cluster host. Verified remote access through public ip is only working when PUBLIC_IP is defined, for example, from a client host, with PUBLIC_IP being 34.216.168.43  on the server host:
```bash
root@ip-172-31-29-112:~# kubectl get pods --all-namespaces
NAMESPACE     NAME …
```
> add public ip support to arktos-up.sh

- pkg/kubeapiserver/authenticator/config.go
- pkg/serviceaccount/jwt.go
- pkg/serviceaccount/jwt_test.go
- pkg/serviceaccount/legacy.go
- pkg/serviceaccount/util.go
- pkg/serviceaccount/util_test.go
- plugin/pkg/admission/security/podsecuritypolicy/admission.go
Part 2 of https://github.com/futurewei-cloud/arktos/issues/38
JWT bearer token is used by service account (SA) authentication. A token is stored as part of the secret generated for a SA. Tenant was missing when a token is generated and as a result during authentication, SA and secrets were fetched only for the "default" tenant. This change does the following:
- add tenant info to the token
- change the authentication to fetch SA and secrets using tenant parsed from token
> add tenant to JWT bearer token authentication

- hack/install-kata.sh
Remove color (red especially) from the output of kata-setup to prevent user from treating this as an error.
Actual output when machine is not Kata campatible:
```bash
* Checking Kata compatibility
time="2020-03-31T03:04:01Z" level=error msg="CPU property not found" arch=amd64 description="Virtualization support" name=vmx pid=11991 source=runtime type=flag time="2020-03-31T03:04:0
1Z" level=warning msg="modprobe insert module failed: modprobe: ERROR: could not insert 'kvm_intel': Operation not supported\n" arch=amd64 error="exit status 1" module=kvm_intel name=ka
ta-runtime pid=11991 source=runtime time="2020-03-31T03:04:01Z" level=error msg="kernel property not found" arch=amd64 description="Intel KVM" name=kvm_intel pid=11991 source=runtime ty
pe=module time="2020-03-31T03:04:01Z" …
```
> removed color from kata-setup output

- pkg/registry/rbac/role/registry.go
- pkg/registry/rbac/validation/rule.go
- pkg/registry/rbac/validation/rule_test.go
- plugin/pkg/auth/authorizer/rbac/BUILD
- plugin/pkg/auth/authorizer/rbac/rbac.go
- staging/src/k8s.io/client-go/listers/rbac/v1/role.go
Fixed a few issues exposed through further test (for demo).
1. service accounts created by the control plane is still using the default tenant. This will cause failure when such service account try to make changes to other tenant such as the case where tenant-controller tries to create namespaces for non-default tenant. 
2. GetRole requires both tenant and namespace
> fixed a few issues for multi-tenancy access control

- pkg/registry/rbac/validation/rule_test.go
RulesFor was missing test cases using a regular tenant. Added now as promised at a [previous PR](https://github.com/futurewei-cloud/arktos/pull/164#discussion_r403387782)
Also changed the output format of the test to show expected and actual instead of the diff. With the diff output one can't tell what ***should be*** the correct output.
> add tests with regular tenant or ruleResolver.RulesFor

- hack/lib/etcd.sh
The original health check for etcd is weird. 
curl -sf means failing silently.
Therefore, I added more check statements.
> Migrated etcd from 3.3.10 to 3.4.4 in scripts

- plugin/pkg/auth/authorizer/rbac/rbac.go
g.Lister.RolesWithMultiTenancy(namespace string, tenant string). This was checked in last October. 
The new code added recently has tenant before namespace instead. 
This is causing rbac to wrongly deny access requests.
Tested with demo setup on aws machines.
> fix mistakenly reversed namespace and tenant in parameter

- cmd/workload-controller-manager/app/config/controllerconfig.go
- cmd/workload-controller-manager/app/controllermanager.go
- cmd/workload-controller-manager/config/controllerconfig.json
- pkg/cloudfabric-controller/deployment/deployment_controller.go
- pkg/cloudfabric-controller/replicaset/replica_set.go
- pkg/registry/core/controllerinstance/storage/storage.go
What type of PR is this?
/kind feature
What this PR does / why we need it:
Currently, controller instance record in registry will be automatically deleted after 5 minutes when it could not renew its lease. This is designed for a very stable environment. However, initial testing often has stability problem and caused workload controller manager restart. Further investigation also found api server does lease renewal every 10 seconds. This change will allow problematic controller instances to be discovered much faster.
Which issue(s) this PR fixes:
Workload controller manager needs to die sooner #174
Special notes for your reviewer:
Please suggest configured values.
I introduced type ControllerConfig, so renamed original ControllerConfig to ControllerConfigMap.
Does this PR introduce a …
> Workload controller manager needs to die sooner #174

- pkg/registry/rbac/clusterrole/registry.go
- pkg/registry/rbac/validation/rule.go
- pkg/registry/rbac/validation/rule_test.go
- plugin/pkg/auth/authorizer/rbac/rbac.go
- plugin/pkg/auth/authorizer/rbac/rbac_test.go
- plugin/pkg/auth/authorizer/rbac/subject_locator_test.go
fix an issue where clusterrolebinding was unable to retrieve cluster role for a tenant.
> fix cluster role getter in rbac for multitenancy

- build/dependencies.yaml
- build/workspace.bzl
- cluster/gce/config-test.sh
- cluster/gce/manifests/etcd-empty-dir-cleanup.yaml
- cluster/gce/manifests/etcd.manifest
- cluster/gce/upgrade-aliases.sh
- cluster/images/etcd-empty-dir-cleanup/Makefile
- cluster/images/etcd/Makefile
- cluster/images/etcd/README.md
- cluster/images/etcd/migrate-if-needed.sh
- cmd/kubeadm/app/constants/constants.go
- cmd/kubeadm/app/constants/constants_test.go
- hack/lib/etcd.sh
- test/utils/image/manifest.go
There will be a change to replace github.com/coreos/etcd by go.etcd.io/etcd  for client shortly. I have to divide the changes into small ones to make it reviewable.
> Migrated etcd 3.3.10 to etcd 3.4.4 cluster server image changes

- pkg/registry/rbac/clusterrole/registry.go
- pkg/registry/rbac/escalation_check.go
- pkg/registry/rbac/validation/rule.go
- plugin/pkg/auth/authorizer/rbac/rbac_test.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation_test.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_apiextensions_client.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/typed/apiextensions/internalversion/apiextensions_client.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/typed/apiextensions/internalversion/customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/typed/apiextensions/internalversion/fake/fake_apiextensions_client.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/typed/apiextensions/internalversion/fake/fake_customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/apiextensions/internalversion/customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/apiextensions/internalversion/interface.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/internalversion/customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/internalversion/expansion_generated.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/strategy.go
- test/integration/etcd/multi_tenancy_data.go
This PR changed scope of CRD from cluster-scope to tenant-scope, so each tenant can have their own CRDs.
For the convenience of reviewers, the PR is split into three commits:
1. the code change to change the scope
2. the update in test files.
3. the auto updated files due to the scope change. This commit includes a big number of line changes, but the reviewer can just skip it.
> Change crd scope

- aws_kube_params.inc
- docs/setup-guide/aws-dev-cluster.md
It's not necessary to use sodu when setup aws cluster. So I update doc to remove it.
Also changed default config of node count from 5 to 2 to save cost.
No
> Remove sudo in aws cluster setup

- staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/BUILD
- staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/controller/establish/establishing_controller.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/controller/nonstructuralschema/nonstructuralschema_controller.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/controller/status/naming_controller.go
- staging/src/k8s.io/apiextensions-apiserver/pkg/controller/status/naming_controller_test.go
- staging/src/k8s.io/apiextensions-apiserver/test/integration/fixtures/resources.go
- staging/src/k8s.io/apiextensions-apiserver/test/integration/main_test.go
- staging/src/k8s.io/apiserver/pkg/endpoints/filters/tenantinfo.go
- test/integration/etcd/BUILD
- test/integration/etcd/etcd_cross_group_test.go
- test/integration/etcd/etcd_storage_path_test.go
- test/integration/etcd/multi_tenancy_data.go
- test/integration/etcd/multi_tenancy_etcd_cross_group_test.go
- test/integration/etcd/multi_tenancy_etcd_storage_path_test.go
- test/integration/etcd/server.go
This PR enable CRD isolation among different tenants. Different tenant can have the CRD of the same G/V/K. The existing crd definition yaml file can continue in each tenant's world. 
To show this, two tenants, qian & peng, are created. And two corresponding contexts, qian-context and peng-context, are created. The following is the test I did in my dev box. 
##############################
create a CRD of foos.samplecontroller.k8s.io in qian's world, using the existing crd.yaml file from the repo, without any change. 
And then an object of the new resource type is created.
The CRD and CRD object are created under the specific tenant
##############################
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl --context=qian-context apply -f …
```
> multi tenancy CRD

- hack/lib/common-var-init.sh
Double brackets implicitly quote all arguments. The APISERVERS_EXTRA is not quoted with single bracket. Updated to double brackets
> Updated single bracket to double brackets

- cmd/kube-apiserver/app/server.go
- vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute/models.go
Update the title/version in swagger.json to reflect the fact that we are now at Arktos v.0.2, instead of Kubernetes v1.15.0.
This change will get us out of the pain to manually update the swagger.json every time after running "make update".
> update title/version in swagger doc

- pkg/controller/tenant/BUILD
- pkg/controller/tenant/tenant_controller.go
- pkg/controller/tenant/tenant_controller_test.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy_test.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
tracking issue https://github.com/futurewei-cloud/arktos/issues/176
A cluster role and rolebinding are created by the tenant controller when a new tenant is created. This role acts as the admin role for the tenant. 
The SA cluster role for tenant-controller has been bumped up to all verb, groups and resource because this role will be assumed to create the default tenant admin role. As a tenant admin role, it would allow "full" access to the tenant's own world. A lower capability role (the tenant-controller role) cannot create a higher capability role (tenant admin role). There are a few such controller role setup in addition to the tenant-controller (full list [here](plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy_test.go)).
Create a tenant **futureweitenant**, and then …
> tenant controller bootstraps cluster role and binding

- staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go
This PR fixed the issue I hit in multi-tenancy-CRD verification: A CRD deletion will get stuck if a resource of the this CRD is created.
The root cause of this bug is that the CRD finalizer needs to delete all of the custom resources before deleting the CRD, but the custom resource lister which get the list of resources has not been changed to be multi-tenancy aware.
I verified the fix in my dev box. 
In this test, I created two tenants, qian&peng, and two contexts, qian-admin-context and peng-admin-context.
##########################
#First, create the same CRD and a resource of this CRD under each tenant
##########################
```
prompt$ kubectl --context=peng-admin-context apply -f ~/gopath/qianc/arktos/staging/src/k8s.io/sample-controller/artifacts/examples/crd.yaml …
```
> make the resource lister in CRD finalizer multi-tenancy-aware

- hack/lib/common-var-init.sh
- hack/lib/common.sh
> /kind bug fix
Fix issue Arktos issue 166. provides an option for not downloading runtime deployment files from runtime repo if a local copy is prefered to use
Fixes 166
Tested locally:
1. Verify normal start of onebox will download runtime deployment files
./hack/arktos-up.sh 
2. with files in local directory, verify flag=false won't download them
OVERWRITE_DEPLOYMENT_FILES=false ./hack/arktos-up.sh 
3. remove the local files and retry to ensure files are downloaded, even flag=false
rm /tmp/* -f -r
OVERWRITE_DEPLOYMENT_FILES=false ./hack/arktos-up.sh
> Option for not downloading runtime deployment files in Arktos onebox setup

- cluster/images/etcd/migrate/migrate_client.go
- cmd/kubeadm/app/phases/upgrade/staticpods_test.go
- cmd/kubeadm/app/util/etcd/etcd.go
- pkg/controller/daemon/daemon_controller.go
- pkg/controller/daemon/daemon_controller_test.go
- pkg/controller/daemon/update.go
- pkg/controller/daemon/update_test.go
- pkg/controller/daemon/util/daemonset_util.go
- pkg/controller/daemon/util/daemonset_util_test.go
- staging/src/k8s.io/apiextensions-apiserver/test/integration/storage/objectreader.go
- staging/src/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/api_object_versioner.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/api_object_versioner_test.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/compact_test.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/errors.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/event.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/event_test.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/healthcheck.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/healthcheck_test.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/lease_manager.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/logger.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/test_server.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/utils.go
- test/integration/daemonset/daemonset_test.go
- test/integration/framework/etcd.go
- vendor/BUILD
```bash
root@ip-172-31-27-32:~/arktos_testing# kubectl --context=futurewei-admin-context create -f futureweids.yaml
daemonset.apps/futurewei-daemonset created
```
Verified daemonset and pod created.
```bash
root@ip-172-31-27-32:~/arktos_testing# kubectl --context=futurewei-admin-context delete -f futureweids.yaml
daemonset.apps "futurewei-daemonset" deleted
```
Verified daemonset and its pod were deleted.
```bash
root@ip-172-31-27-32:~/arktos_testing# kubectl create -f futureweids.yaml
daemonset.apps/futurewei-daemonset created
root@ip-172-31-27-32:~/arktos_testing# kubectl delete -f futureweids.yaml
daemonset.apps "futurewei-daemonset" deleted
```
> multi-tenancy daemonset 

- pkg/apis/core/types.go
- pkg/kubeapiserver/server/insecure_handler.go
- staging/src/k8s.io/api/core/v1/types.go
- staging/src/k8s.io/apimachinery/pkg/api/validation/BUILD
- staging/src/k8s.io/apimachinery/pkg/api/validation/generic.go
- staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- staging/src/k8s.io/apiserver/pkg/endpoints/filters/tenantinfo.go
- staging/src/k8s.io/apiserver/pkg/endpoints/filters/tenantinfo_test.go
- staging/src/k8s.io/apiserver/pkg/endpoints/installer.go
- staging/src/k8s.io/cli-runtime/pkg/resource/builder.go
- staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
This PR address the issue to explicitly indicate whether a request targets all-tenants. So, with this change, for a request from a system user:
1. GET /api/v1/namespaces: means lists namesapces of system tenants
2.  GET /api/v1/tenants/all/namespaces: means lists namesapces of all the tenants, including the system tenants and regular tenants
TenantAll is "", similar to NamespaceAll in K8s, which is also "" . By making TenantAll as an empty string, the list operation on etcd is quite simple. Therefore, I did not change the definition of TenantAll in Arktos. When Arktos detects the tenant is "all" in the url, the tenant will be set TenantAll. If tenant is empty in the url, the tenant will be set according to short-path logic. 
Tests done in my local dev box:
``` …
```
> explicit tenant all in url

- pkg/controller/service/patch.go
- pkg/controller/service/patch_test.go
- pkg/controller/service/service_controller.go
- pkg/controller/service/service_controller_test.go
- pkg/kubelet/dockershim/libdocker/fake_client.go
- pkg/kubelet/kuberuntime/helpers_linux_test.go
- pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go
```bash
TENANT            NAMESPACE             NAME                            HASHKEY               READY   STATUS    RESTARTS   AGE
system            default               pod/my-nginx-5dc984b54d-z675b   4657253913366147043   1/1     Running   0          25s
system            default               pod/my-nginx-5dc984b54d-zl7t9   4449315009755198168   1/1     Running   0          25s
futureweitenant   futurewei-namespace   pod/my-nginx-5dc984b54d-pfftg   590654163509119680    1/1     Running   0          21s
futureweitenant   futurewei-namespace   pod/my-nginx-5dc984b54d-szmzj   2206163685672492177   1/1     Running   0          21s
TENANT            NAMESPACE             NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
system            default …
```
> make service controller multi-tenant

- pkg/apis/core/validation/validation.go
- pkg/kubectl/cmd/create/create_tenant.go
- pkg/kubectl/generate/versioned/tenant.go
- pkg/kubectl/generate/versioned/tenant_test.go
- pkg/registry/core/tenant/storage/storage_test.go
- test/yaml/apiserver_partition/tenant1.yaml
- test/yaml/apiserver_partition/tenant2.yaml
- test/yaml/multi_tenancy_examples/tenant1.yaml
- test/yaml/multi_tenancy_examples/tenant2.yaml
This PR fixes the issue "kubectl create tenant" no longer works due to the requirements StorageClusterId must be specified when creating a new tenant, introduced in https://github.com/futurewei-cloud/arktos/commit/e99e24c64791966b57215078b2dab4a32e75f15c.
Before this change, I hit the following error in my dev box:
```
qianchen@qianchen-VirtualBox:~$ kubectl create tenant test-tenant
The Tenant "test-tenant" is invalid: spec.storageClusterId: Required value: must specify storage cluster id
```
WIth this change, user can specify the storageClusterId when creating a new tenant via the the new commandline option --storagecluster. If this option is not used, the storageclusterId will be set to "1" by default.
Tests done in my dev box:
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ …
```
> fix kubectl-create-tenant

- cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
- cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go
/kind: bugfix
Running the following command for scalability tests in AWS failed.
source aws_kube_params.inc && ./cluster/kube-up.sh
Debugging showed the failure was due to the following error:
"the tenant in the use info kubernetes-admin is empty"
It was verified the kube-up.sh succeeded after applying the fix.
> fix failure in aws kube-up

- aws_kube_params.inc
- cluster/aws/util.sh
- cluster/kube-up.sh
In Jenkins CI, it needs majority steps which is to generating binaries, scripts for preset machines, but don't execute it. It delays executing to be run by Jenkins clients. So in this pr it introduced a new flag that indicating the process only generate scripts but not execute it.
/kind feature
> Add a flag IS_DRY_RUN which will be used in Jenkins CI

- cluster/aws/util.sh
Fix issue that kubemark cannot start, error: permission denied when copying .kube config. The issue is because there is an extra "@" in the code which fails operation.
/kind bug
> Fix issue that kubemark cannot start, error: permission denied when copying .kube config

- pkg/kubelet/kubelet.go
- pkg/quota/v1/evaluator/core/pods.go
- plugin/pkg/admission/limitranger/BUILD
- plugin/pkg/admission/limitranger/admission.go
- plugin/pkg/admission/resourcequota/BUILD
- plugin/pkg/admission/resourcequota/controller.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
**What this PR does / why we need it**: Vertical Scaling needs to work with resource quota and limit ranges. This PR adds that support.
**Which issue(s) this PR fixes**: #223 
Fixes #
Tested this by creating a resource-quota limiting CPUs to 4, and creating pod and updating (attempting) beyond the quota, as well as within the quota.
For limit range, create a limitrange with min 2 cpu, max 5 cpu, and resize within and outside the bounds. The latter fails.
**Does this PR …
> In-place Pod Vertical Scaling - add resource-quota & limit-ranger support

- pkg/controller/tenant/tenant_controller.go
- pkg/controller/tenant/tenant_controller_test.go
- test/integration/tenantcontroller/tenantcontroller_test.go
Create the system tenant at boostrap.
Verification Done in Dev Box:
Right after the cluster is up by arktos-up.sh, run the following commands:
```
qianchen@qianchen-VirtualBox:~$ ETCDCTL_API=3 etcdctl get "" --prefix=true --keys-only | grep tenants
/registry/tenants/system
qianchen@qianchen-VirtualBox:~$ kubectl create tenant system
Error from server (AlreadyExists): tenants "system" already exists
```
> create system tenant at tenant controller bootstrap

- pkg/controller/resourcequota/resource_quota_controller.go
- pkg/controller/resourcequota/resource_quota_controller_test.go
- pkg/controller/resourcequota/resource_quota_monitor.go
- pkg/quota/v1/evaluator/core/persistent_volume_claims.go
- pkg/quota/v1/evaluator/core/pods.go
- pkg/quota/v1/evaluator/core/services.go
- pkg/quota/v1/generic/evaluator.go
- pkg/quota/v1/interfaces.go
- pkg/quota/v1/resources.go
- plugin/pkg/admission/resourcequota/admission.go
- plugin/pkg/admission/resourcequota/admission_test.go
- plugin/pkg/admission/resourcequota/controller.go
- plugin/pkg/admission/resourcequota/resource_access.go
- test/integration/quota/BUILD
- test/integration/quota/quota_test.go
This changes convert the resource quota controller to multi-tenant. This resource quota is within a certain tenant.
The unit tests and integration tests are modified. Will bring in more manual tests but review can start now.
> multi-tenancy resource quota controller (per tenant)

- pkg/registry/rbac/validation/BUILD
- pkg/registry/rbac/validation/rule.go
fix https://github.com/futurewei-cloud/arktos/issues/377
verfication done in local dev box ( following the same procedure as in issue 377):
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl create tenant tenant-1
tenant/tenant-1 created
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ hack/setup-multi-tenancy/setup_client.sh tenant-1 admin
setting up context tenant-1-admin-context for tenant-1/admin in group tenant-1-group at host localhost
generating a client key tenant-1.key...
creating a sign request tenant-1.csr...
creating an tenant certificate tenant-1-admin.crt and get it signed by CA
Setting up tenant context...
cleaned up tenant-1.csr
***************************
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl …
```
> fix issue 377

- pkg/controller/tenant/tenant_controller.go
- pkg/controller/tenant/tenant_controller_test.go
fix for https://github.com/futurewei-cloud/arktos/issues/423
Admin user in a tenant cannot pass authorization to create pod
The cluster role and rolebinding created for admin user is missing rules for nonresourceurls. It was working before because previously we added system tenant rules as a workaround fix to make testing pass. This fix was removed in [this commit](https://github.com/futurewei-cloud/arktos/commit/e8c1a21242c33ff3b159c62522ba9ae5d21c7e09) and hence the problem was exposed.
Added missing rules. 
https://github.com/kubernetes/kubernetes/issues/53349
Create pod and deployments following the process user used in the issue:
```bash
root@ip-172-31-27-32:~/code/src/k8s.io/arktos# kubectl create tenant tenant-1
tenant/tenant-1 created …
```
> add missing rule policy to tenant admin clusterrole

- staging/src/k8s.io/apiserver/pkg/authentication/group/group_adder.go
- staging/src/k8s.io/apiserver/pkg/authentication/group/group_adder_test.go
- test/integration/auth/accessreview_test.go
- test/integration/auth/auth_test.go
- test/integration/auth/rbac_test.go
- test/integration/master/synthetic_master_test.go
These tests were using the old-format user info when the multi-tenancy cert and token work was not done. It is time to use the new tenant-aware user info now.
> using new tenanted user info in integration tests

- staging/src/k8s.io/client-go/rest/request.go
These code was in place to set the tenant value in the REST request before "short-path" was introduced. With the introduction of "short-path", this logic is no longer needed.
It verifies the system is still working after this change
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubeclt create tenant aaaa
kubeclt: command not found
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl create tenant aaaa
tenant/aaaa created
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl create ns bbbb --tenant aaaa
namespace/bbbb created
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl get ns -AT
TENANT   NAME              STATUS   AGE   TENANT
aaaa     bbbb              Active   9s    aaaa
aaaa     default           Active   33s …
```
> remove out-dated code in request.go

- pkg/kubectl/cmd/create/create_tenant.go
- pkg/kubectl/generate/versioned/BUILD
- pkg/kubectl/generate/versioned/tenant.go
- pkg/kubectl/generate/versioned/tenant_test.go
This PR fix the break in command "kubectl create tenant" due to the recent change in the type of StorageClusterId.
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl create tenant abcdef
setting storage cluster to 0
tenant/abcdef created
```
before this change, the command breaks as follows:
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl create tenant abcdef
The Tenant "abcdef" is invalid: spec.storageClusterId: Invalid value: "system": must be integer 0-63
```
> fix kubectl-create-tenant break due to StorageClusterId type change

- pkg/kubectl/cmd/rollingupdate/rollingupdate.go
- pkg/kubectl/cmd/rollout/rollout_history.go
- pkg/kubectl/cmd/rollout/rollout_pause.go
- pkg/kubectl/cmd/rollout/rollout_restart.go
- pkg/kubectl/cmd/rollout/rollout_resume.go
- pkg/kubectl/cmd/rollout/rollout_status.go
- pkg/kubectl/cmd/rollout/rollout_undo.go
- pkg/kubectl/cmd/scale/scale.go
- pkg/kubectl/history.go
- pkg/kubectl/rollback.go
- pkg/kubectl/rolling_updater.go
- pkg/kubectl/rolling_updater_test.go
- pkg/kubectl/scale.go
- pkg/kubectl/scale_test.go
- pkg/kubectl/util/deployment/deployment.go
- staging/src/k8s.io/client-go/scale/BUILD
- staging/src/k8s.io/client-go/scale/client.go
- staging/src/k8s.io/client-go/scale/fake/BUILD
- staging/src/k8s.io/client-go/scale/fake/client.go
- staging/src/k8s.io/client-go/scale/interfaces.go
- test/utils/update_resources.go
This PR makes the command "kubectl scale" and "kubectl rollout" support the command line option of "--tenant".
This PR also fixed the issues of https://github.com/futurewei-cloud/arktos/issues/434 and https://github.com/futurewei-cloud/arktos/issues/433.
Without this change, the "kubectl scale" command would report "not found" error.
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl get deployment sample-nginx-deployment --tenant sample-tenant-1 --namespace sample-namespace-a
NAME                      HASHKEY               READY   UP-TO-DATE   AVAILABLE   AGE
sample-nginx-deployment   4296895824068558264   0/3     3            0           1s
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl scale --replicas=5 deployment/sample-nginx-deployment --tenant …
```
> Multi tenancy/kubectl rollout/scale

- cmd/kube-controller-manager/app/controllermanager.go
- pkg/controller/network/network_controller.go
>
/kind bug
> /kind design
> /kind flake
Disalbe NetworkController by default. Current NetworkController is only for Neutron Network, so
disable it by default and only enable it when using Neutron
Fixes # issue #471
```release-note
```
> Networkcontroller only start when using Neutron as network

- staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
- staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go
This PR fixes the issue https://github.com/futurewei-cloud/arktos/issues/479
```
qianchen@qianchen-VirtualBox:~$ kubectl create tenant aaa
setting storage cluster to 0
tenant/aaa created
qianchen@qianchen-VirtualBox:~$ kubectl get ns --tenant aaa
NAME          STATUS   AGE   TENANT
default       Active   7s    aaa
kube-public   Active   7s    aaa
kube-system   Active   7s    aaa
qianchen@qianchen-VirtualBox:~$ kubectl delete ns default --tenant aaa
Error from server (Forbidden): namespaces "aaa/default" is forbidden: this namespace may not be deleted
qianchen@qianchen-VirtualBox:~$ kubectl delete ns kube-system --tenant aaa
Error from server (Forbidden): namespaces "aaa/kube-system" is forbidden: this namespace may not be deleted
```
```
qianchen@qianchen-VirtualBox:~$ kubectl delete …
```
> fix issue 479

- build/root/Makefile
- hack/setup-dev-node.sh
> /kind bug
1) Make "sudo" working for Make targets like quick-release or other targets, instead of mandate "sudo -E".  By default "sudo" won't preserve the PWD environment variable.
2) Fix a comment typo in setup-dev-node.
> Update scripts to be more compatible with sudo and also correct a comment typo

- README.md
- docs/README.md
Changes:
1. The architecture diagram doesn't show up in README even the URL is right.  Change it to raw URL.  
A local test shows it works. Need to check in to verify on Github.
> Fix the picture link in README with raw URL

- perf-tests/clusterloader2/cmd/BUILD
- perf-tests/clusterloader2/cmd/clusterloader.go
- perf-tests/clusterloader2/pkg/config/cluster.go
- perf-tests/clusterloader2/pkg/framework/BUILD
- perf-tests/clusterloader2/pkg/framework/config/BUILD
- perf-tests/clusterloader2/pkg/framework/config/client_config.go
- perf-tests/clusterloader2/pkg/framework/framework.go
- perf-tests/clusterloader2/pkg/test/simple_test_executor.go
- perf-tests/clusterloader2/pkg/util/util.go
- staging/src/k8s.io/client-go/dynamic/BUILD
- staging/src/k8s.io/client-go/dynamic/simple.go
. Allow perf-test to get all api servers in partitioned api server environment
. Support list from revision in dynamic client
. Sonya: dynamic to create namespaces and force to average namespace name per apiserver number
Scheduling throughput on 2 partitioned api servers:
{
"perc50": 20,
"perc90": 20,
"perc99": 20.2,
"max": 23.4
}
for Arktos changes:
https://github.com/Sindica/arktos/commits/2apiserver-sonya-verified
> Perf-test changes

- pkg/apis/core/helper/qos/qos.go
- pkg/apis/core/v1/helper/qos/qos.go
> /kind bug
Fix a timing issue encountered in perf testing
Fixes # 552
there are 3 possible options in fixing this bug:
1. Always set spec.workloadinfo when admitting the pod, so all subsequent calls when assuming the workloadinfo set already, and pod.spec will be all read-only operations
2. R/W lock to the QoS () function
3. use a localcopy of spec instead of the global *pod.
the current fix picks #3 which is least invasive and safe fix to unblock perf testing.
None
> Fix a timing issue where the pod.spec.workloadinfo can be used concurrently by PLEG and podUpdate routines

- cmd/workload-controller-manager/app/config/controllerconfig.go
- cmd/workload-controller-manager/app/controllermanager.go
- cmd/workload-controller-manager/config/controllerconfig.json
- pkg/cloudfabric-controller/controllerframework/controllerinstancemanager.go
- staging/src/k8s.io/client-go/tools/cache/reflector.go
. Use 12 hours as the base of resync Period (same as kube controller manager)
. Correct controller instance manager metrics
. Add resyncPeriod & WatchListPageSize to ListAndWatch log
> Miscellanous fix of WCM:

- pkg/cloudfabric-controller/controllerframework/cim_test.go
- pkg/cloudfabric-controller/controllerframework/controller_framework.go
- pkg/cloudfabric-controller/controllerframework/controller_framework_test.go
- pkg/cloudfabric-controller/controllerframework/controller_framework_utils.go
- pkg/cloudfabric-controller/controllerframework/controllerinstancemanager.go
- pkg/cloudfabric-controller/replicaset/replica_set_test.go
- test/integration/cloudfabriccontrollers/deployment_util.go
- test/integration/cloudfabriccontrollers/framework_test.go
- test/integration/cloudfabriccontrollers/testutil.go
Previous controller name use individual generated uuid. Since the controllers watch pods based on owner reference key, the randomized generation logic can cause all controllers watch all pods during perf test.
Force controllers in the same controller managers have similar controller name allows a workload controller manager only watch a small portion of pods.
Example controller names:
NAME                                              CONTROLLERTYPE   UID                                    CONTROLLERKEY         WORKLOADNUM   ISLOCKED
deployment-**0b857ad2-0496-42e6-8a5a-06cec6fabe09**   Deployment       3bcf2c98-dc83-4da4-8af6-53995097c98e   1844674407370955163   0             false
deployment-3de8ea83-4814-4d9f-8f5a-78192baeeb9b   Deployment       89d22ae9-df11-4d10-98a1-88d97952aa77 …
> Update controller name generation logic for data distribution efficiency

- perf-tests/clusterloader2/run-e2e.sh
**Issue** : perf-tests/clusterloader2/run-e2e.sh is the entry script to run perf-tests in kubernetes. However, our project is named "arktos" yet the code has many dependencies in "k8s.io/kubernetes", running this script in arktos leads to build failures.  Perf test team found a workaround, which creates a kubernetes soft link in parallel to the "arktos" folder and run the script from "kubernetes" folder. This workaround is surely not a clean solution. 
This PR fixes this issue.
> make run-e2e.sh run without softlink

- pkg/scheduler/algorithm/predicates/predicates.go
- pkg/scheduler/algorithm/predicates/predicates_test.go
/kind bug
It fixes the bug in scheduler code that node-runtime-readiness predicate did not respect pod's no-schedule toleration.
A common pattern for clsuter to bootstrap is starting Arktos without CNI plugin, then installing CNI plugin (like Flannel) later via k8s facilities(daemonset etc). However, before the CNI is successfully installed, the nodes' runtimes are in not-ready state. Becuase the node-runtime-readiness predicate fails to fit cni pod with these nodes, hence cni pods won't be scheduled, leading to CNI cannot be installed - forming a dead lock.
To break such a lock, there are a few reasonable ways:
1. to bypass runtime readiness check when pod has no-schedule toleration, or
2. to bypass runtime readiness …
> bug fix: scheduler node runtime readiness predicate should respect pod no-schedule toleration

- test/e2e/BUILD
- test/e2e/arktos/multi_tenancy/cmd/BUILD
- test/e2e/arktos/multi_tenancy/cmd/framework/BUILD
- test/e2e/arktos/multi_tenancy/cmd/framework/errors.go
- test/e2e/arktos/multi_tenancy/cmd/framework/testcase.go
- test/e2e/arktos/multi_tenancy/cmd/framework/testconfig.go
- test/e2e/arktos/multi_tenancy/cmd/framework/testsuite.go
- test/e2e/arktos/multi_tenancy/cmd/framework/util.go
- test/e2e/arktos/multi_tenancy/cmd/testrunner.go
- test/e2e/arktos/multi_tenancy/run-e2e-test.sh
- test/e2e/arktos/multi_tenancy/test_suites/tenant_init_delete_test.yaml
This PR replaces the bash-script based tool with a new one, which is written in golang. This change bring the following benefits:
1. Allowing more complex test command
2. Allowing More incisive test result analysis
3. easier code maintenance & better extensibility
Also included in this PR is a sample test suite file, tenant_init_delete_test.yaml.
Run test/e2e/arktos/multi_tenancy/run-e2e-test.sh
This script will build the binary and run the tool with configuration defined in the .sh script
The features of this tool is comparable to the previous command-line based tool. Here are some screenshots:
1. The tool will complain if the test Arktos cluster is not ready for test
2. The sample test suite succeeded
3. break the sample test suite file to showcase the test failure
> Rewrite multi-tenancy e2e test tool in golang

- test/e2e/arktos/multi_tenancy/run-e2e-test.sh
- test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_deployment_replicaset_controller.yaml
- test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_endpoints_controller.yaml
- test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_sa_token_controller.yaml
- test/e2e/arktos/multi_tenancy/testdata/sample-deployment.yaml
This PR adds the e2e test suites for the following multi-tenancy controllers:
1. deployment & replicaset controller
2. serviceaccount & token controller
3. endpoints controllers.
The test suites were verified in my dev box. The following are the screenshots:
Tracking issue: https://github.com/futurewei-cloud/arktos/issues/559
> e2e tests for deployment/replicaset/serviceacount/token/endpoints controllers

- test/e2e/arktos/multi_tenancy/cmd/framework/testcase.go
- test/e2e/arktos/multi_tenancy/cmd/framework/testsuite.go
- test/e2e/arktos/multi_tenancy/cmd/testrunner.go
- test/e2e/arktos/multi_tenancy/run-e2e-test.sh
- test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_deployment_replicaset_controller.yaml
This PR enhances the multi-tenancy e2e test tool per comments from the team members and my own experience. It is part of work for https://github.com/futurewei-cloud/arktos/issues/559
The changes made are:
The test case author can define them to print some user-friendly message as the test goes on. The following is a screenshot of a test run after I added such definitions (only one test suite file change is included in this PR to have a clear-cut PR. ):
Test suite file validation will fail if there are undefined fields. The previous behavior is skipping it. This helps catch the typo of test case authors.
As a result, I can specify the following in run-e2e-test.sh
```
test_suite_files="multi_tenancy_controller/test_*_controller.yaml"
```
Instead of something like
``` …
```
> improve multi-tenancy e2e test tool

- hack/lib/common-var-init.sh
- test/yaml/vm_default.yaml
- test/yaml/vm_with_persistedVolumes/vm_aws_static_pv.yaml
- test/yaml/vm_with_persistedVolumes/vm_datadisk_flexvol.yaml
- test/yaml/vm_with_persistedVolumes/vm_datadisk_pv.yaml
- test/yaml/vm_with_persistedVolumes/vm_rootfs_pv.yaml
bump up runtime version to enable vertical scaling feature for vm
arktos 830 release
None
None api level. vm pod yaml will need to set the cpu model that supports numa node.
**Testing:
```
root@ip-172-31-10-115:/work/src/github.com/Mirantis/virtlet# kubectl get pods --all-namespaces
NAMESPACE     NAME                        HASHKEY               READY   STATUS    RESTARTS   AGE
kube-system   kube-dns-5d69f5657d-775jw   3992330385106179963   3/3     Running   0          57s
kube-system   virtlet-rzgg8               1061567349605714443   3/3     Running   0          41s …
```
> bump up runtime version

- pkg/kubectl/cmd/create/create_clusterrole.go
- pkg/kubectl/cmd/create/create_cronjob.go
- pkg/kubectl/cmd/create/create_role.go
- pkg/kubectl/describe/versioned/describe.go
This PR fixes issues https://github.com/futurewei-cloud/arktos/issues/631 and https://github.com/futurewei-cloud/arktos/issues/641
"--tenant" option is working with "kubectl create cronjob". The resource created will be under the expected tenant. 
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl create cronjob test-cronjob --image=busybox --schedule="*/1 * * * *" --tenant x
cronjob.batch/test-cronjob created
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl get cronjob -AT
TENANT   NAMESPACE   NAME           SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
x        default     test-cronjob   */1 * * * *   False     0        <none>          8s
```
"--tenant" option is working with "kubectl create role". The resource created will be under the expected tenant. …
> fix bug 631/641

- hack/setup-multi-tenancy/setup_client.sh
This PR is part of work for multi-tenancy e2e tests (https://github.com/futurewei-cloud/arktos/issues/648). It updates the tool of kube config per the requirements of multi-tenancy e2e tests.
1. Add the ability to remove the context setup. So the contexts created during the e2e tests can be cleaned up.
2. The location of the client key and cert files are moved from pwd to /tmp. This helps keep the repo clean. 
The user is also able to customize the location of the client key and cert files now.
3. Return an non-zero exit code if there are errors. Also, the error messages will be printed.
4. update the help message based on the above changes. 
1. The same command line as now to create user context
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl config view
apiVersion: v1 …
```
> update setup_client.sh for e2e tests

- test/e2e/arktos/multi_tenancy/run-e2e-test.sh
- test/e2e/arktos/multi_tenancy/test_suites/admission/test_cross_tenant.yaml
- test/e2e/arktos/multi_tenancy/test_suites/admission/test_tenant_exists.yaml
- test/e2e/arktos/multi_tenancy/testdata/sample-pod.yaml
This PR adds the following e2e test suites for multi-tenancy admission controller:
1. test TenantExists admission controller
2. test cross-tenant is banned for regular tenants and works for system tenants
Verification:
All tests passed locally in my dev box.
Tracking work item: https://github.com/futurewei-cloud/arktos/issues/648
> Multi tenancy/admission e2e tests

- staging/src/k8s.io/client-go/apiserverupdate/update.go
- staging/src/k8s.io/client-go/apiserverupdate/update_test.go
- staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
- staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager_test.go
This commit https://github.com/futurewei-cloud/arktos/commit/bed33f520ab694b96d117cc3e7368f0db64d2785 had a deadlock in api server partition. This PR is intended to fix it.
> Bug fix for API Server Config Update Notification

- cmd/kubemark/BUILD
- cmd/kubemark/hollow-node.go
- pkg/kubemark/BUILD
- pkg/kubemark/hollow_kubelet.go
/kind bug
this PR ensures the arktos kubeclient initialized in hollow-node code path.
Hollow-node starts kubelet in a sort-of simplified way, which would bypass the initialization of arktos clientset object in _regular_ kubelet start code, which leads to nil reference panic in kubemark run. see error log as in next section
```
0904 05:19:22.711084       6 file.go:68] Watching path "/tmp/hollow-kubelet.490124287/static-pods068816210"
I0904 05:19:22.711116       6 kubelet.go:315] Watching apiserver
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2fd4662]
goroutine 1 [running]: …
```
> hollow-node initializes arktos kube-client

- pkg/kubelet/network/dns/BUILD
- pkg/kubelet/network/dns/dns.go
- pkg/kubelet/network/dns/dns_test.go
/kind feature
this PR ensures the pod's associated network is of ready state, and the dns service has IP address assigned.
NONE
> kubelet starts pod after network is ready and dns service has IP assigned

- test/e2e/arktos/multi_tenancy/run-e2e-test.sh
- test/e2e/arktos/multi_tenancy/test_suites/crd/test_per_tenant_crd.yaml
- test/e2e/arktos/multi_tenancy/test_suites/crd/test_system_share_crd.yaml
- test/e2e/arktos/multi_tenancy/testdata/forced_share_crd.yaml
- test/e2e/arktos/multi_tenancy/testdata/forced_share_crd_resource.yaml
- test/e2e/arktos/multi_tenancy/testdata/regular_crd.yaml
- test/e2e/arktos/multi_tenancy/testdata/regular_crd_resource.yaml
This PR adds the following e2e test suites for multi-tenancy CRD:
1. test per-tenant CRD
2. test sytem-share CRD
Verification:
All tests passed locally in my dev box.
Tracking work item: https://github.com/futurewei-cloud/arktos/issues/648
> multi-tenancy CRD e2e tests

- test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_deployment_replicaset_controller.yaml
- test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_endpoints_controller.yaml
- test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_sa_token_controller.yaml
- test/e2e/arktos/multi_tenancy/test_suites/tenant_init_delete_test.yaml
This PR updated the e2e test cases for multi-tenancy controllers and tenant-init-delete. The changes include:
1. add user-friendly messages 
2. quick return of clean-up commands to speed up the tests. 
3. Add selflink info check on the resources objects. Tests have been designed to check resources of different scope, namely the cluster-scoped tenant, tenant-scoped namespace and namespace-scoped deployment.
Verification:
All tests passed locally in my dev box.
Tracking work item: https://github.com/futurewei-cloud/arktos/issues/648
> update multi-tenancy controller/tenant-init e2e test cases

- cmd/edgegateway/app/options/options.go
- pkg/apis/edgegateway/v1/types.go
- pkg/cloudgateway/cloudhub/servers/httpserver/server.go
- pkg/cloudgateway/cloudhub/servers/httpserver/signcerts.go
- pkg/edgegateway/common/constants/default.go
- pkg/edgegateway/edgehub/certificate/certmanager.go
- pkg/edgegateway/edgehub/common/certutil/certfile.go
- pkg/edgegateway/edgehub/common/http/http.go
- pkg/edgegateway/edgehub/edgehub.go
when edgegateway is started, edgegateway gets certificates from cloudgateway if the certificates don't exist.
then, edgegateway connects to cloudgateway through certificate.
> edgegateway gets certificates from cloudgatway

- cmd/arktos-network-controller/app/BUILD
- cmd/arktos-network-controller/app/controller.go
- cmd/arktos-network-controller/app/controller_test.go
- cmd/arktos-network-controller/app/wellknown_service.go
This PR creates the well-known kubernetes for a network object.
Verification:
1. start the test cluster by running arktos-up.sh.
2. Create the network CRD, by running
```
kubectl create -f pkg/controller/artifacts/crd-network.yaml
```
3. create tenant x
```
kubectl create tenant x
```
4. Start the arktos network controller
```
./_output/bin/arktos-network-controller --kubeconfig=/home/qianchen/.kube/config
```
Where the config is:
```
qianchen@qianchen-VirtualBox:~$ kubectl config view
apiVersion: v1
clusters:
- cluster:
server: http://127.0.0.1:8080
name: local
contexts:
- context:
cluster: local
user: ""
name: local-ctx
current-context: local-ctx
kind: Config
preferences: {}
users: []
```
5.  create a flat-type network object and see the kubernetes service is created:
``` …
```
> create per-tenant-network kubernetes service

- pkg/controller/mizar/mizar-pod-controller.go
- pkg/controller/mizar/util.go
Currently there is no hostIP sent to grpc server for newly created pod.
When a pod got created, there will be 1 create event triggered and 5 update events triggered. At the time the create event and first update event happens, there is no hostIP yet. And at this time mizar pod controller is sending the data to grpc server without hostIP data. The followed 4 update events have hostIP data, but in the event queue, the update event is being handled and existing in the queue, then the 4 followed update events are dedup'd by queue, which means the 4 followed update events cannot enqueue. Hence when first update event handle completed, there is no more event to be handled in the queue, so eventually there is no hostIP data sent to grpc server.
The solution is to add an EventTime field in the …
> Fix issue that no hostIP sent to grpc server

- hack/arktos-up.sh
/kind bug
Arktos-up.sh installs network CRD before entering the loop of waiting for node be ready
NONE
> arktos-up: install network crd before waiting for node ready

- hack/arktos-up.sh
This PR fixes the issue that "kubectl get net" return error complaining the "net" is not a valid resource type, though CRD networks.arktos.futurewei.com has already been installed in the arktos-up.sh.
Analysis & Solution:
The bug is due to that resource discovery cache is not updated after the new CRD type is created. So this script adds a line of "kubectl api-resources" to force a cache refresh.
Verification:
In the local dev box, right after the Arktos cluster is up by arktos-up.up, run the following command:
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl get net
No resources found.
```
The error message before this change was gone.
> fix kubectl-get-net error

- hack/arktos-cni.rc
- hack/arktos-up.sh
/kind bug
This change in arktos-up bootstrap process is to ensure the common cni binaries is installed. 
This installation is necessary, as some external cni plugins (like new versions of flannel) does not install the binaries by themselves, bu trely on the binaries(e.g. loopback, flannel, bridge, host-local 7 portmap - required by flannel) exist on the system instead.
NONE
> arktos-up: installs the common cni binary package for the external cni plugin that will be installed later

- docs/design-proposals/multi-tenancy/multi-tenancy-network.md
/kind design
This PR clarifies the current supporrt of per-network kubernetes endoints: get verb is supported; watch/list not directly supported.
NONE
> clarifies current support of per-network kubernetes EPs

- cmd/arktos-network-controller/app/controller.go
- cmd/arktos-network-controller/app/controller_test.go
- cmd/arktos-network-controller/app/dns_deployment.go
- cmd/arktos-network-controller/app/dns_deployment_test.go
- cmd/arktos-network-controller/network-controller.go
- docs/setup-guide/arktos-enforces-netowrk-feature.md
/kind bug
This PR makes coredns pods of per-network DNS deployment connecting to the specified kube-apiserver.
When a network resource is created, arktos network controller creates its per-network DNS deployment; however, at this moment, the controller might not have any idea of the per-network kubernetes service IP (for external IPAM networks) - actually it uses 10.0.0.1 by default,  leading to coredns unable to get hold of the api server, thus cannot start properly.
Making the DNS deployment to define its pod template so that coredns pod connects to kube-apiserver directly solve this kubernetes service ip not yet assigned issue.
In the long run, the controller may need to wait for per-network kubernetes service IP …
> coredns pod connects to kube-apiserver directly

- pkg/apis/storage/validation/validation.go
- pkg/apis/storage/validation/validation_test.go
- pkg/kubectl/describe/versioned/describe.go
- pkg/kubectl/describe/versioned/describe_test.go
- pkg/kubectl/describe/versioned/multi_tenancy_describe_test.go
- pkg/registry/storage/storageclass/storage/storage_test.go
- pkg/registry/storage/storageclass/strategy.go
- pkg/registry/storage/storageclass/strategy_test.go
- staging/src/k8s.io/api/storage/v1/types.go
- staging/src/k8s.io/api/storage/v1beta1/types.go
- staging/src/k8s.io/client-go/informers/storage/v1/interface.go
- staging/src/k8s.io/client-go/informers/storage/v1/storageclass.go
- staging/src/k8s.io/client-go/informers/storage/v1beta1/interface.go
- staging/src/k8s.io/client-go/informers/storage/v1beta1/storageclass.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1/fake/fake_storage_client.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1/fake/fake_storageclass.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1/storage_client.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1/storageclass.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1beta1/fake/fake_storage_client.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1beta1/fake/fake_storageclass.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1beta1/storage_client.go
- staging/src/k8s.io/client-go/kubernetes/typed/storage/v1beta1/storageclass.go
- staging/src/k8s.io/client-go/listers/storage/v1/expansion_generated.go
- staging/src/k8s.io/client-go/listers/storage/v1/storageclass.go
- staging/src/k8s.io/client-go/listers/storage/v1beta1/expansion_generated.go
- staging/src/k8s.io/client-go/listers/storage/v1beta1/storageclass.go
- test/integration/etcd/multi_tenancy_data.go
This PR fixes issue https://github.com/futurewei-cloud/arktos/issues/758. 
This PR changes the scope of resource StorageClass to tenant-scope. As StoragClass is conceptually a dynamic PersistentVolume, it should have the same resource scope. 
MultiTenancy APIs for storageclass, including StorageClassesWithMultiTenancy, are generated. 
As shown, different tenants can create storageclass objects in its own space.
```
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl create tenant x
setting storage cluster to 0
tenant/x created
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ kubectl get storageclass -AT
TENANT   NAME                 PROVISIONER               AGE
system   standard (default)   kubernetes.io/host-path   107s
qianchen@qianchen-VirtualBox:~/gopath/qianc/arktos$ …
```
> Update storageclass scope

- docs/design-proposals/multi-tenancy/multi-tenancy-network.md
- docs/setup-guide/arktos-enforces-netowrk-feature.md
- docs/setup-guide/arktos-enforces-network-feature.md
- docs/setup-guide/multi-node-dev-cluster.md
- hack/lib/common.sh
- hack/runtime/default_mizar_network.json
This PR makes miscellaneous updates per feedback from the Mizar team on Mizar-Arktos integration.
1. Update docs/instructions.
2. Find tune the Arktos-up.sh to support a default network template for mizar.
Verified in the my dev box, when env var ARKTOS_NETWORK_TEMPLATE=mizar, the default network object created under the system tenant when the Arktos cluster is up is:
```bash
NAME      TYPE    VPC                      PHASE   DNS
default   mizar   system-default-network    
```
> update doc per feedback from the Mizar team

- build/lib/release.sh
- cluster/common.sh
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/manifests/BUILD
- cluster/gce/manifests/etcd-grpc-proxy.manifest
- cluster/gce/util.sh
This PR allows perf tests to enable etcd-grpc-proxy based on the environement variables. 
If env var START_ETCD_GRPC_PROXY=true, the grpc proxy will be kicked off and the kube-apiserver will connect to the proxy port. Otherwise, kube-apiserver will talk to the etcd core server directly.
During 5k-node perf tests, we see a lot of "took too long" warnings in the core etcd server log and also many etcd delay warnings in Kube-Apiserver logs.  As the etcd grpc proxy offloads the core etcd server by coalescing the watch requests (more details are available in https://etcd.io/docs/v3.1.12/op-guide/grpc_proxy/), we tried to enable the grpc proxy to see whether it solves this issue. 
As the test run results (<em>logs can be found under GCP project: workload-controller-manager on sonya-uswest2: …
> etcd grpc proxy

- cmd/kube-controller-manager/app/controllermanager.go
- hack/arktos-up-scale-out-poc.sh
- hack/lib/common.sh
with this fix, pod is able to start up and running
```bash
Every 2.0s: kubectl get pods -o wide                                                                                                                                           goose-t: Wed Nov  4 02:45:49 2020
NAME                    HASHKEY               READY   STATUS    RESTARTS   AGE     IP           NODE      NOMINATED NODE   READINESS GATES
k8s-vanilla-pod         8546537340999228980   1/1     Running   0          3m12s   10.88.0.33   goose-r   <none>           <none>
nginx-669ffc87d-fp49z   735652811459332087    1/1     Running   0          84s     10.88.0.34   goose-r   <none>           <none>
```
> fixed issue with the setup

- hack/scale_out_poc/two_TP/nginx.conf
- hack/scale_out_poc/two_TP/setup_nginx_proxy.sh
This change add scripts to config the nginx proxy for two TPs & one RP.
Run:
TENANT_PARTITION_ONE_IP=172.31.26.146  TENANT_PARTITION_TWO_IP=172.31.26.99  RESOURCE_PARTITION_IP=172.31.23.48 hack/scale_out_poc/two_TP/setup_nginx_proxy.sh
> nginx proxy setting with two TPs

- cmd/kubelet/app/options/options.go
- cmd/kubelet/app/server.go
- cmd/kubemark/hollow-node.go
- hack/arktos-up-scale-out-poc.sh
- hack/lib/common.sh
- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_getters.go
- pkg/kubelet/kubelet_node_status.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/kubelet_test.go
- pkg/kubelet/pod_actions.go
- pkg/kubelet/runonce_test.go
- pkg/kubelet/volume_host.go
- pkg/kubemark/hollow_kubelet.go
Initial code change to expand kubelet to support multiple Tenant partitions and separation of Resource and Tenant partition clientsets.
make and run:
run it with new args:
/kubelet --kubeconfig=/testconfig/kubeconfig1 --tenant-servers="http://10.1.1.1:8080,http://10.1.1.2:8080" > kubelet.log 2>&1 &
OR to set up the resource cluster with:
export TENANT_SERVERS="http://172.31.10.115:8080,http://172.31.14.52:8080" && export SCALE_OUT_PROXY_ENDPOINT="http://172.31.10.115:8888" && LOG_LEVEL=3 KUBE_CONTROLLERS=nodelifecycle IS_RESOURCE_PARTITION=true ./hack/arktos-up-scale-out-poc.sh
Noted that it uses a new cmdline args for now. add new entries to kubecofig will involved in the client-go config update which currently i incline to not change.
```
Below is a quick testing with them. Issue #1 and …
```
> Expand kubelet's clientset to support multiple tenant partitions

- pkg/kubelet/kubelet.go
For now for POC of scale-out design, let's use multiple pod update channels to avoid pods being removed due to merge logic in kubelet's podConfig.
pods can staying in running with the fix now.
```
root@ip-172-31-10-115:/# kubectl --kubeconfig=/testconfig/kubeconfig1 get pods -AT -w
TENANT   NAMESPACE   NAME          HASHKEY               READY   STATUS    RESTARTS   AGE
a        default     condefault1   259074526838791798    1/1     Running   0          32m
a        default     testpod1      6614589983344413142   1/1     Running   2          176m
```
> use different update channel for multiple api server partitions

- pkg/kubelet/kubelet.go
- pkg/kubelet/runonce_test.go
- pkg/kubelet/status/status_manager.go
Pod status update is changed to use the kube client based on the tenant. 
The switch logic is based on the current proxy setting
```
location ~* ^/apis/[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+/tenants/[a-m0-9_.-]+/(.*) {
proxy_pass $tenant_api_one;
}
location ~* ^/apis/[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+/tenants/[n-z_.-]+/(.*) {
proxy_pass $tenant_api_two;
}
```
Current only letter is used and will be updated later with numbers and other characters after pod is working end to end.
On local 2t1p environment. Pod status is updated correctly to "ContainerCreating" in the correct tenant partition.
Issue: Pod is showing unintended deletion. Debugging this now, hence the #do-not-merge
> pod status update using multiple kube clients

- cluster/gce/util.sh
- hack/scale_out_poc/nginx.conf
This PR fixes the issue that the node lifecycle controller cannot get the node-lease from the lister when connecting to nginx proxy.
The cause is due to the following forward logic in nginx.conf:
location ~ ^/apis/coordination.k8s.io/**v1**/leases?(.*) {
proxy_pass $RESOURCE_API;
}
Yet, arktos use version V1beta1 for node-lease requests. As a result, node-leases are not correctly forwarded.
Tested in my dev env, the NodeNotReady issue was gone.
> fix NodeNotReady issue

- cmd/kubelet/app/server.go
- hack/scale_out_poc/two_TP/nginx.conf
- pkg/kubelet/kubelet.go
- pkg/kubelet/secret/secret_manager.go
This fix sets kubelet to use the correct kube client for secrets list and watch. Without it, pod creation was failing on the 2nd tenant partition during volume mounting. 
Validated end to end on local environment. 
On tenant partition 1
```bash
root@goose-t:~/code/src/k8s.io/arktos/test/yaml# kubectl get pods --tenant alex -o wide
NAME              HASHKEY               READY   STATUS    RESTARTS   AGE   IP            NODE      NOMINATED NODE   READINESS GATES
k8s-vanilla-pod   3683182769778565890   1/1     Running   0          32s   10.88.3.108   goose-r   <none>           <none>
```
On tenant partition 2
```bash
root@goose-3:~/code/src/k8s.io/arktos/test/yaml# kubectl get pod --tenant oxygen -o wide
NAME              HASHKEY               READY   STATUS    RESTARTS   AGE   IP …
```
> fix secret list and watch

- cmd/kubemark/hollow-node.go
- pkg/kubelet/kubelet.go
- test/kubemark/resources/hollow-node_template.yaml
- test/kubemark/start-kubemark.sh
support two tenant partitions in kubemark hollow-node type. currently hardcoded with two tenant partition in scripts.
In Testing...
-->
```release-note
```
> Kubemark hollow-node to support multiple tenant partitions

- pkg/kubelet/kubelet.go
- pkg/kubelet/secret/secret_manager.go
- pkg/kubelet/status/status_manager.go
if only one kubeclient is provided (most likely for a phase one merge), switch kubelet to use it. 
Validate on local environment with
1. 2 tp 1 rp, 2 endpoints in TENANT_SERVERS
2. 1 tp 1 rp, 1 endpoint in TENANT_SERVERS
Pod goes into running into both cases.
> add fallback to kubeclient 0 if only one is provided

- cluster/gce/util.sh
- test/kubemark/gce/util.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
**What this PR does / why we need it**: Nginx proxy is flaky. Cluster verification script that talks to the apiserver via proxy intermittently fails and this can cause the cluster bringup script to take a long time to start or intermittently fail. Verifying directly against apiserver is a reliable way to ensure actual cluster is fine. The test will still use proxy as per architecture.
Fixes #
**Does this PR introduce a user-facing …
> Modify cluster verification to bypass proxy and directly talk to cluster apiserver

- hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
- hack/scale_out_poc/haproxy_2T1R/setup_haproxy.sh
HaProxy config for m2. 
To run it:
```
TENANT_PARTITION_ONE_IP=##.##.##.##  TENANT_PARTITION_TWO_IP=##.##.##.## RESOURCE_PARTITION_IP=##.##.##.## setup_haproxy.sh
```
> config haproxy for scale-out m2

- hack/scale_out_poc/haproxy_1T1R/haproxy.cfg
- hack/scale_out_poc/haproxy_1T1R/setup_haproxy.sh
This script configs a HAProxy for Scale-Out M1. 
Verified in local 1T1R environment. 
To Run the script: 
```
TENANT_PARTITION_IP=##.##.##.## RESOURCE_PARTITION_IP=##.##.##.## setup_haproxy.sh
```
> haproxy setup script

- cmd/kubelet/app/server.go
- pkg/kubelet/configmap/configmap_manager.go
- pkg/kubelet/kubelet.go
- pkg/kubelet/pod/mirror_client.go
- pkg/kubelet/runonce_test.go
- pkg/kubelet/secret/secret_manager.go
- pkg/kubemark/hollow_kubelet.go
Converted a few more kubeclient usage to using correct tenant partition
deployment and pod started up and then deleted correctly on local 2TP1RP environment.
getTPClient is being repeated. ugly. will refactor likely after the next PR (pv, volume, etc) is done.
> convert kubeclient to support multiple tenant partition 

- cmd/kube-controller-manager/app/core.go
- pkg/controller/nodelifecycle/scale_out_poc_util.go
Make node-controller backwards compatible. When "tenant-servers" in the CLI option is empty, use the apiserver specified in the kubeconfig. 
Verified in gce, the issue that nodelifecycle controller crash issue in kube-up.sh is solved.
> backwards compatible node controller

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
- cmd/kubelet/app/server.go
- cmd/kubemark/hollow-node.go
- hack/scale_out_poc/nginx.conf
- test/kubemark/gce/util.sh
- test/kubemark/start-kubemark.sh
In testing, but sharing the code changes in case one is interested in knowing what they are.
the issue with kube-up.sh is understood. it is due to the kube-controller-manager failed to start at the m2 branch with the tenant-server parameter is missing. Qian is working on a fix at the nodelifecycle controller to bring back compat in place.
remove the WIP to get this PR going forward.
Testing is being done in perf test run env as:
1. kube-up.sh to bring up the admin cluster
2. start-kubemark.sh to start the perf test cluster
3. (optional) run end to end load test.
```
export MASTER_DISK_SIZE=200GB MASTER_ROOT_DISK_SIZE=200GB KUBE_GCE_ZONE=us-central1-a MASTER_SIZE=n1-highmem-32 NODE_SIZE=n1-highmem-16 NUM_NODES=1 NODE_DISK_SIZE=200GB GOPATH=$HOME/go KUBE_GCE_ENABLE_IP_ALIASES=true …
```
> Pickup changes in M1 branch into M2 branch

- hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
This PR fixes the hidden bug in forwarding logic in haproxy.cfg.
This change make requests from tenant named all#### ( but not all) to TP-1, requests from tenant named system#### ( but not system) to TP-2. There was a bug that will treat tenants named system### like "system", all### as "all".
Verification:
Check the haproxy log to make sure the following requests generated by the following commands run in TP-1 and TP-2 are forwarded as expected:
```
kubectl get pods --tenant aaa
Always forwarded to TP-1
```
```
kubectl get deployments --tenant aaa
Always forwarded to TP-1
```
```
kubectl get pods --tenant zzz
Always forwarded to TP-2
```
```
kubectl get deployments --tenant zzz
Always forwarded to TP-2
```
```
kubectl get pods -AT
Always forwarded to source partition
```
```
kubectl get …
```
> fix haproxy.cfg

- cluster/common.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/partitionserver-configure-helper.sh
- cluster/gce/util.sh
- hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
- test/kubemark/gce/util.sh
- test/kubemark/resources/hollow-node_template.yaml
- test/kubemark/start-kubemark.sh
- test/kubemark/stop-kubemark.sh
This PR enables the 2T1R kubemark test cluster setup. It includes the following work:
1. disable WCM (picking code change from Sonya)
2. the dynamic creation of haproxy config
3. Reorder cluster creation and add tenant-servers to RP controller starts up commandline (Yunwen's PR 849 was integrated)
The code is verified e2e in gce with the following command lines:
```
export MASTER_ROOT_DISK_SIZE=100GB MASTER_DISK_SIZE=200GB KUBE_GCE_ZONE=us-west1-b MASTER_SIZE=n1-highmem-32 NODE_SIZE=n1-highmem-8 NUM_NODES=2 NODE_DISK_SIZE=200GB KUBE_GCE_NETWORK=qianc-arktos GOPATH=$HOME/go KUBE_GCE_ENABLE_IP_ALIASES=true KUBE_GCE_PRIVATE_CLUSTER=true CREATE_CUSTOM_NETWORK=true KUBE_GCE_INSTANCE_PREFIX=qianc-arktos APISERVERS_EXTRA_NUM=0 SCALEOUT_CLUSTER=true SCALEOUT_CLUSTER_TWO_TPS=true …
```
> set up 2T1R kubemark clusters with haproxy dynamic configured

- cmd/kubelet/app/server.go
- pkg/controller/volume/persistentvolume/pv_controller.go
- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/status/status_manager.go
- pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
- pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
- pkg/kubelet/volumemanager/reconciler/reconciler.go
- pkg/kubelet/volumemanager/reconciler/reconciler_test.go
- pkg/kubelet/volumemanager/volume_manager.go
1. fix a bug that causes statefulset to fail for non-system tenant
2. add kubeclient selection based on tenant 
- statefulset with hostpath pvc created and deleted correctly on both tenant partitions
- no regression with pod and deployment creation and deletion
- TP kubeclient is still duplcated
- add this in tenant partition to allow host path pv: export ENABLE_HOSTPATH_PROVISIONER=true
- need further code on node status update
> statefulset fix and kubeclient switch

- perf-tests/clusterloader2/pkg/execservice/exec_service.go
- perf-tests/clusterloader2/pkg/framework/client/objects.go
- perf-tests/clusterloader2/pkg/framework/framework.go
- perf-tests/clusterloader2/pkg/imagepreload/imagepreload.go
- perf-tests/clusterloader2/pkg/measurement/common/bundle/test_metrics.go
- perf-tests/clusterloader2/pkg/measurement/common/metrics_for_e2e.go
- perf-tests/clusterloader2/pkg/measurement/common/probes/probes.go
- perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
- perf-tests/clusterloader2/pkg/measurement/util/object_store.go
- perf-tests/clusterloader2/pkg/prometheus/prometheus.go
- perf-tests/clusterloader2/pkg/test/simple_test_executor.go
- perf-tests/clusterloader2/pkg/util/multi-tenancy.go
- staging/src/k8s.io/client-go/dynamic/dynamicinformer/informer.go
This PR allows the perf tests running under a specific non-system tenant, whose name is specified in the env var SCALEOUT_TEST_TENANT.
Verified in gce kubemark cluster as follows:
1. created a 2T1R kubemark test environment
2.  manually create a tenant named aaa in TP-1
2. Running the following commandline:
```
SCALEOUT_TEST_TENANT=aaa perf-tests/clusterloader2/run-e2e.sh --nodes=100 --provider=kubemark --kubeconfig=/home/cloudshare/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark-tp-1 --report-dir=/home/cloudshare/perf-logs --testconfig=testing/density/config.yaml --testoverrides=./testing/experiments/use_simple_latency_query.yaml
```
I checked:
1. the test completed (though I got some timeout issues in pod deletion, the test itself was running to completion)
2. all the …
> multi-tenancy perf-test

- hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
the original maxconn value (2048) is too small. Increase it to 500K per backend. 
As doc online, a haproxy is able to process 2M connections. 
Reference https://www.freecodecamp.org/news/how-we-fine-tuned-haproxy-to-achieve-2-000-000-concurrent-ssl-connections-d017e61a4d27/#:~:text=HAProxy%20Configuration,-This%20is%20probably&text=The%20maxconn%20setting%20allows%20us,support%20overall%20(one%20way).&text=The%20max%20open%20files%20has,being%20set%20at%202%20million.
> set larger haproxy maxconn for scale out tests

- cluster/gce/util.sh
we found the * entry doesn't seem work for the root account, as we can see the nofile is 1024 when issue ulimit -a under root account.
explicitly set this for root and haproxy account to ensure the nofile setting for them.
verified in testing:
```
ybai2016@new-yb01-k8s-scaleout-kubemark-proxy:~$ sudo su -
root@new-yb01-k8s-scaleout-kubemark-proxy:~# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 837329
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200 …
```
> Append limits.conf to explictly set for root and haproxy

- staging/src/k8s.io/apimachinery/pkg/watch/watch.go
- cherry pick https://github.com/CentaurusInfra/arktos/commit/3a8629f40d1c01c1ec32cab74408ce9be3113256
- left out added tests due to this being poc
- fixing "fatal error: concurrent map iteration and map write"
- no regression with pod, deployment and statefulset
- kubelet not crashing within reasonable amount of times and tries
> cherry pick commits to fix concurrent map error

- cluster/gce/gci/configure-helper-common.sh
It will allow the default network object to be created in Tenant Partitions. Hopefully it will remove the 404 errors to Get tenants/####/networks/default objects in api servers.
> enable the creation of default network object in kubemark

- cluster/gce/gci/configure-helper.sh
- cluster/gce/util.sh
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: This fixes a bug where admin cluster would not come up. It starts prometheus process on tenant and resource partition master nodes only.
Fixes #
```release-note
```
> Enable prometheus only on tenant & resource masters in scaleout arch

- pkg/kubelet/kubelet.go
- pkg/kubelet/pod/mirror_client.go
- pkg/kubelet/types/pod_update.go
When support for multiple tenant partition cluster was added, we explicitly differentiate the "source" of api server as api0 , api1 etc. with a suffix of digit for each partitions. however, this breaks the logic with , at least, the static pod check where relies on the source=="api".
quick fix for now, is to check the prefix of the source, instead of the full string comparison.
verified with 100 node perf run.
```
ybai2016@new-yb01-k8s-scaleout-minion-group-1655 /var/log $ grep -i "Creating a mirror pod" kubelet-hollow-node-*.log
ybai2016@new-yb01-k8s-scaleout-minion-group-1655 /var/log $ 
```
> Quick fix of handling mirror pod issue

- cluster/gce/util.sh
add a reset to prevent haproxy failure to start when it's restarted too quickly
manually tested on 5k haproxy vm
> fix haproxy failure due to restarting too quickly

- cluster/gce/gci/configure-helper-common.sh
- pkg/kubelet/network/dns/dns.go
- staging/src/k8s.io/client-go/util/flowcontrol/throttle.go
- test/kubemark/start-kubemark.sh
As scalability test is bothered by too many requests to get network object, whose work is not completely in place yet. To improve the performance of apiserver, this PR removes the defintion and usage of network CRD in scalablity tests.
Verified in one BOX:
1. deployment creation/scale succeeded
2. apiserver.log and haproxy.log showed there is not request to "GET "tenants/####/networks/default" any more
> remove network CRD and object retrieval for scalability tests

- cluster/gce/gci/configure-helper-common.sh
Fixing a typo in the name of mizar controllers.
Verified with 100-node kubemark run.
> fix mizar-controller name typo

- cluster/gce/util.sh
- hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
Fixed the crash when haproxy is restarted when starting 2tp1rp cluster.
Tested using 100-node, 1000-node and 5k node cluster. Cluster came up correctly and prometheus metrics showed up too.
> fix the haproxy crash after patching for prometheus

- cluster/gce/util.sh
- hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
- hack/scale_out_poc/haproxy_2T1R/setup_haproxy.sh
Recent changes to haproxy.cfg to add Prometheus monitoring to proxy breaks the one-box haproxy setup. This PR fixes it by removing those lines when generating the haproxy.cfg.
Also included in this PR:
1. increase the number of processes of haproxy from 32 to 64 ( the max value allowed) as we have very powerful machines in tests.
2. code refactoring
Verification:
1. verified in my local env that it works.
2. Verified that the clusters were built after integrating with the Haproxy Prometheus fix (https://github.com/CentaurusInfra/arktos/pull/895)
> fix haproxy cfg & script to work in one-box

- cluster/gce/util.sh
- test/kubemark/start-kubemark.sh
Verified.
With this change, "cat /proc/sys/net/netfilter/nf_conntrack_max" returned 26214400 in Tp-1/Tp-2/RP machines.
> enlarge net.netfilter.nf_conntrack_max when building scale-out masters

- perf-tests/clusterloader2/pkg/chaos/nodes.go
- perf-tests/clusterloader2/pkg/framework/client/objects.go
- perf-tests/clusterloader2/pkg/imagepreload/imagepreload.go
- perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
- perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
- perf-tests/clusterloader2/pkg/prometheus/experimental.go
- perf-tests/clusterloader2/pkg/test/simple_test_executor.go
- statefulset.yaml
This PR fixes the issue that density test fails when the test tenant does not belong to the default TP.
Verification:
Combining this PR with https://github.com/CentaurusInfra/arktos/pull/902 and https://github.com/CentaurusInfra/arktos/pull/897, a test cluster with 3 TPs and 1 RP was created. Density tests succeeded for each of the following three tenants:
1. arktos ( home TP: TP1)
2. memphis ( home TP: TP2)
3. zeta (home TP: TP3)
> make density test work on non-default TP

- pkg/kubelet/config/config.go
- pkg/kubelet/configmap/configmap_manager.go
- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/pod/mirror_client.go
- pkg/kubelet/secret/secret_manager.go
- pkg/kubelet/status/status_manager.go
- pkg/kubelet/util/util.go
- pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
- kubelet supports using kube clients from more than 2 tenant partitions
- remove duplication of GetTPClient (finally!)
cannot test more than 2 tenants though without proxy change.
- one box test with 2 tenants (done)
- 100-node test with arktos tenant (done)
> Extend kubelet to use kubeclient from more than 2 tenant partitions

- pkg/kubelet/kubelet_pods.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/internal/cache/cache.go
- pkg/scheduler/scheduler.go
Update some key logging entries to level 2 so that they can be visible in perf run with default logging level settings.
> Debug logging in kubelet and scheduler

- cluster/gce/gci/configure-helper-common.sh
- hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
- hack/scale_out_poc/haproxy_2T1R/setup_haproxy.sh
- make haproxy emit log only to /var/log/haproxy.log in **one-box environment**. 
- build the same haproxy with prometheus in one-box environment
- this changes apply to 2-tp 1-rp setup script. a second PR will follow to make the same changes in the N tp and 1 rp script that is also used for GCE setup
- enable prometheus scraping to scheduler 
- enable prometheus scraping to controller
- prior to this change, haproxy log is either flooding /var/log/syslog, or writing to both /var/log/syslog and /var/log/haproxy.log
- consistent haproxy version with the one used in GCE
- help debugging and analysis in one-box
- change is based on https://pc-freak.net/blog/enable-haproxy-logging-separate-log-varloghaproxylog-prevent-haproxy-duplicate-messages-varlogmessages/
- metrics info in …
> separate and direct haproxy and add scheduler & controller prometheus

- go.mod
- staging/src/k8s.io/apimachinery/go.mod
- staging/src/k8s.io/apiserver/go.mod
- staging/src/k8s.io/cli-runtime/go.mod
- staging/src/k8s.io/client-go/go.mod
- staging/src/k8s.io/cloud-provider/go.mod
- staging/src/k8s.io/cluster-bootstrap/go.mod
- staging/src/k8s.io/code-generator/go.mod
- staging/src/k8s.io/component-base/go.mod
- staging/src/k8s.io/cri-api/go.mod
- staging/src/k8s.io/csi-translation-lib/go.mod
- staging/src/k8s.io/kube-aggregator/go.mod
- staging/src/k8s.io/kube-controller-manager/go.mod
- staging/src/k8s.io/kube-proxy/go.mod
- staging/src/k8s.io/kube-scheduler/go.mod
- staging/src/k8s.io/kubectl/go.mod
- staging/src/k8s.io/kubelet/go.mod
- staging/src/k8s.io/legacy-cloud-providers/go.mod
- staging/src/k8s.io/metrics/go.mod
- staging/src/k8s.io/node-api/go.mod
- staging/src/k8s.io/sample-apiserver/go.mod
- staging/src/k8s.io/sample-cli-plugin/go.mod
- staging/src/k8s.io/sample-controller/go.mod
Due to the recent change to repo github.com/mholt/caddy, start-kubemark.sh will fail in a machine which does not have a cached golang package of mholt/caddy.
This PR fixed this issue and verified in gce machine qiandev, which hit the issue before.
> fix mholt/caddy reference issue

- cluster/gce/util.sh
- hack/scale_out_poc/config_haproxy/haproxy.cfg.template
- hack/scale_out_poc/config_haproxy/setup_haproxy.sh
This is the 2nd part of changes for haproxy logging after https://github.com/CentaurusInfra/arktos/pull/906.
- one box: cluster start and sanity test runs correctly. haproxy log shows up only in /var/log/haproxy.log
- GCE: 100-node density test passes. logs correct.
> make haproxy dump logs only to /var/log/haproxy.log (part 2)

- cluster/gce/gci/configure-helper-common.sh
to CR: simply it missed a "(", but just a number there will make it more clear for the higher cap of api server memory target.
20K cluster is up with this fix.
> fix issue with invalid cmd/synctax

- perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
- perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
- perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
This PR fixes the issue that multi-tenancy may grab the data of wrong tenant and thus lead to unexpected failure.
Verified this issue is fixed.
> Fix cross tenant gather

- cluster/gce/util.sh
- test/kubemark/resources/hollow-node_template_scaleout.yaml
- test/kubemark/start-kubemark.sh
>
kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: This helps verify that max open files configuration for haproxy is correctly configured for all processes.
**Which issue(s) this PR fixes**: Perf cluster deployment (kube-up + start-kubemark) has regressed in scale-out-poc branch for non scale-out architecture (scale-up). This partially fixes the regression. Currently, the non scaleout cluster fails in start-kubemark due to kubemark binary unable start if tenant & resource server params are missing. The binary should …
> Partial fix for kube-up & start-kubemark for non-scaleout cluster

- cmd/kubelet/app/options/options.go
- cmd/kubelet/app/server.go
- hack/setup-dev-node.sh
- pkg/kubelet/kubelet.go
1. kubelet changes in this PR works with in-secure port. Will be updated when the changes for secure port are ready
2. usage of created tenant partition clients will come in PRs that follows this one
1. update setup-dev-node.sh with golang 1.13.9
2. kubelet code for taking tenant-servers parameters
1. Arktos-up came up correctly
2. Created and deleted the follow resources correctly
```
kubectl create tenant zeth
kubectl create -f /tmp/web.yaml --tenant zeth
kubectl create deployment nginx --image=nginx --tenant zeth
kubectl create -f vanilla.yaml --tenant zeth
kubectl create tenant apple
kubectl create -f /tmp/web.yaml --tenant apple
kubectl create deployment nginx --image=nginx --tenant apple
kubectl create -f vanilla.yaml --tenant apple
```
> various changes for scale-out (1st of many more)

- cmd/kubemark/hollow-node.go
hollow node backcompat support. this follows the same approach as kubelet cmd/app/server.go does.
Tested with latest POC branch with Vinay's PR
> fix backcompat issue in hollow-node

- pkg/kubelet/network/dns/dns.go
- pkg/kubelet/network/dns/dns_test.go
It was found that turning off the multi-tenancy network CRD feature ( as it has not completed) helps improve the scalability. This PR turns off this feature in master branch. 
This feature was turned on/off per the setting of feature gate value of "MandatoryArktosNetwork".
Verification:
It is verified that by default setting, the kubelet does not send out request like "tenant/aaa/networks/default" to apiserver.
> migrate the code change about network CRD to master

- pkg/controller/volume/persistentvolume/pv_controller.go
- pkg/kubelet/kubelet_pods.go
Fix PVC issue due to missing multi-tenancy. Symptom is pvc going into LOST status unable to bound with PV.
1. Arktos-up came up correctly
2. Created and deleted the follow resources correctly
```
kubectl create tenant zeth
kubectl create -f /tmp/web.yaml --tenant zeth
kubectl create deployment nginx --image=nginx --tenant zeth
kubectl create -f vanilla.yaml --tenant zeth
kubectl create tenant apple
kubectl create -f /tmp/web.yaml --tenant apple
kubectl create deployment nginx --image=nginx --tenant apple
kubectl create -f vanilla.yaml --tenant apple
```
This bug also needs to have an e2e test. Due to the time constrain for scale-out release this will be added after scale-out kubelet poc migration is done. Tracking in https://github.com/CentaurusInfra/arktos/issues/938
> fix for pv & pvc with multi-tenancy

- staging/src/k8s.io/apiserver/pkg/registry/rest/meta.go
Due to https://github.com/CentaurusInfra/arktos/issues/790, there are excessive messages of "invalid uuid" in the apiserver logs of scalability tests. Yet we know this reset-uid operation is not blocking the test. So we lower the log level to have a cleaner log.
THis change has been verified in previous a 10K*2 test run in PoC branch.
> reduce the reset-uuid message log level to 3

- cmd/kubelet/app/BUILD
- cmd/kubelet/app/server.go
- hack/arktos-up.sh
- pkg/kubelet/BUILD
- pkg/kubelet/config/BUILD
- pkg/kubelet/config/config.go
- pkg/kubelet/kubeclientmanager/BUILD
- pkg/kubelet/kubeclientmanager/kubeclient_manager.go
- pkg/kubelet/kubeclientmanager/kubeclient_manager_test.go
- pkg/kubelet/kubelet.go
The new kubeclient manager provides the kubeclient for a specific tenant. In specific:
1. registers tenant with its corresponding apisever id
2. looks up and returns kubeclient based on tenant/apiserver id mapping
The actual usage of this kubeclient manager will be in a few following PRs.
1. Arktos-up came up correctly
2. Created and deleted the follow resources correctly
```
kubectl create tenant zeth
kubectl create -f /tmp/web.yaml --tenant zeth
kubectl create deployment nginx --image=nginx --tenant zeth
kubectl create -f vanilla.yaml --tenant zeth
kubectl create tenant apple
kubectl create -f /tmp/web.yaml --tenant apple
kubectl create deployment nginx --image=nginx --tenant apple
kubectl create -f vanilla.yaml --tenant apple
```
> add kubeclient manager for scale-out

- cmd/cloud-controller-manager/app/controllermanager.go
- cmd/controller-manager/app/serve.go
- cmd/kube-apiserver/app/aggregator.go
- cmd/kube-apiserver/app/testing/BUILD
- cmd/kube-apiserver/app/testing/testserver.go
- cmd/kube-controller-manager/app/controllermanager.go
- cmd/kube-scheduler/app/server.go
- cmd/workload-controller-manager/app/controllermanager.go
- cmd/workload-controller-manager/app/serve.go
- hack/arktos_copyright_copied_k8s_files
- pkg/master/master.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
- staging/src/k8s.io/apiserver/pkg/server/BUILD
- staging/src/k8s.io/apiserver/pkg/server/config.go
- staging/src/k8s.io/apiserver/pkg/server/config_test.go
- staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
- staging/src/k8s.io/apiserver/pkg/server/filters/goaway.go
- staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go
- staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
- staging/src/k8s.io/apiserver/pkg/server/healthz.go
- staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
- staging/src/k8s.io/apiserver/pkg/server/healthz/healthz_test.go
- staging/src/k8s.io/apiserver/pkg/server/hooks.go
- staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
- staging/src/k8s.io/apiserver/pkg/server/options/server_run_options_test.go
- staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
- test/integration/master/kube_apiserver_test.go
10K single cluster density test is currently having "etcdserver: too many requests" issue. Pick up community https://github.com/kubernetes/kubernetes/pull/88567 just in case it helps.
Other cherry pick changes are due to dependencies.
Plus Arktos copy right setting.
1/25 density test data looks better than 1/15 & 1/21. apiserver_current_inflight_request is much smooth and closer to 1.18. This is a good cherry-pick
Arktos 1/25/2021
1.18
> 1.18 Goaway changes

- cmd/kubemark/BUILD
- cmd/kubemark/hollow-node.go
- pkg/kubemark/hollow_kubelet.go
kubemark to adopt the scale-out kubelet changes
1. Arktos-up.sh came up correctly, and created and deleted the follow resources correctly
```
kubectl create tenant zeth
kubectl create -f /tmp/web.yaml --tenant zeth
kubectl create deployment nginx --image=nginx --tenant zeth
kubectl create -f vanilla.yaml --tenant zeth
kubectl create tenant apple
kubectl create -f /tmp/web.yaml --tenant apple
kubectl create deployment nginx --image=nginx --tenant apple
kubectl create -f vanilla.yaml --tenant apple
```
2. kubemark 100-node cluster & 100-node density tests
startup latencies also normal.
> kubemark changes for kubelet scale-out migrated code

- pkg/cloudfabric-controller/client_builder.go
- pkg/controller/client_builder.go
We hit the issue in PoC branch where the QPS of some controllers is abnormally high, which is caused by different controllers share the same KubeConfig object. A workaround was provided in https://github.com/CentaurusInfra/arktos/pull/885.
Yet later it was found this QPS issue only happens when the controller-manager is started with "--use-serviceaccount-credentials" option turned off. The root cause is that all the controllers share the  same kubeconfig object in insecure mode. 
The workaround we had in PoC branch is an overkill as it also touches the code path of secure mode. This PR gives a clean fix by letting all the controllers, in **insecure** mode, own its own KubeConfig object. 
In PoC branch, I reverted the previous workaround and applied this fix, then printed out the …
> fix QPS issue in insecure mode

- pkg/kubelet/kubelet_node_status.go
use resource partition client for node ops
1. one box sanity
2. 100-node kubemark density test
> switch to rp client for node

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Currently in master branch, ENABLE_APISERVER_SECURE_PORT is broken, kube-up does not work. This fixes the issue for scaleup architecture by passing the ENABLE_APISERVER_SECURE_PORT to master vm configuration script, and uses ports 8080/8888 appropriately for scaleout architecture while retaining normal operation for scaleup.
Tested this by deploying 1TP-1RP cluster in scale-out-poc branch, and deploying ENABLE_INSECURE_PORT set to true as well as false and …
> Use insecure port in configs only for scaleout architecture

- pkg/controller/vmpod/vm_controller.go
- pkg/kubelet/container/helpers.go
- pkg/kubelet/container/helpers_test.go
- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/status/BUILD
- pkg/kubelet/status/status_manager.go
- pkg/kubelet/status/status_manager_test.go
- pkg/util/pod/BUILD
- pkg/util/pod/pod.go
- pkg/util/pod/pod_test.go
- test/e2e/node/BUILD
- test/e2e/node/pods.go
kubelet: Avoid sending no-op patches
Ensure Kubelet always reports terminating pod container status
This change was perf tested on 1/21 & 1/25
> 1.18 improvement kubelet

- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_getters.go
- pkg/kubelet/kubelet_node_status.go
- pkg/kubelet/kubelet_node_status_test.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/kubelet_test.go
This PR is mostly refactor to eventually retire the kubeClient used in Kubelet and fully adopt kubeTPClients. A following PR will take on the heavy lifting of the volume related fix.
Also one functional fix to use heartbeatclient for node status. 
1. local 1-box
2. 100-node density scale-up
> refactor to retire KubeClient in Kubelet

- cluster/gce/util.sh
For scale-out, do not evaluate GCE_PRIVATE_CLUSTER for network
1. local 1-box
2. 100-node scale-up
3. 100-node scale-out
> fix issue that causes wrong service tier in scale-out

- cluster/common.sh
- cluster/gce/util.sh
- hack/scale_out_poc/config_haproxy/haproxy.cfg.template
- test/kubemark/gce/util.sh
- test/kubemark/start-kubemark.sh
- test/kubemark/stop-kubemark.sh
>
> /kind bug
/kind design
> /kind flake
**What this PR does / why we need it**: Currently we use insecure port 8080 for all API communication in scaleout architecture. This PR does two things:
1. Secures the client ---- haproxy communication to use SSL with certificates generated by proxy as CA. (Intra-scaleout communication is still insecure after this PR. Yunwen will have a PR for that after integrating with this)
2. Cleanup several unnecessary and confusing intermediate kubeconfigs that are generated as part of scaleout cluster deployment. …
> Secure client--proxy API for scaleout, and remove generation of unnecessary kubeconfig files

- perf-tests/clusterloader2/testing/experiments/disable_pvs.yaml
- perf-tests/clusterloader2/testing/load/deployment.yaml
Scale-out and Scale-up load tests both failed due ot PV/PVC processing of deployments&statefulsets. The deployments/statefulset which uses volumes will never get the pods in "Running" state.  As we are continuing to solve issue (tracked in https://github.com/CentaurusInfra/arktos/issues/978), this PR provides a switch to skip this issue temporarily.
When the env var  CL2_ENABLE_PVS is set to false, the test deployments&statefulsets will be created without attaching to PVs.
This PR was tested on top of https://github.com/CentaurusInfra/arktos/pull/976, which fixed another error in load-test, and I got the following result:
1. Scale-up 100-node load test succeeded with commandline test-configs "--testconfig=testing/load/config.yaml --testoverrides=./testing/experiments/disable_pvs.yaml".
1. …
> add a switch to disable PV in load test

- hack/make-rules/update.sh
- pkg/controller/mizar/mizar-node-controller.go
- pkg/controller/mizar/mizar-pod-controller.go
- pkg/controller/mizar/mizar-service-controller.go
Currently in mizar pod and service controller, when deleting the object, the code will try to retrieve the object. Since the object has already been deleted, the deleting operation will always trigger an error.
The issue happens only when mizar is running because it happens in mizar controllers.
The fix: when deleting object, don't retrieve it at that time. Instead, just send the name, namespace, tenant info to mizar backend for deleting.
/kind bug
Current pod and service deleting will always throw error for mizar controllers.
> Fix pod/service deleting issue

- hack/lib/version.sh
- pkg/version/VERSION.sh
With this change, CI tools and dev local environments no longer need to change KUBE_GIT_VERSION when Arktos version is updated.
Each Arktos release will need to update pkg/version/VERSION.sh
> Read Arktos version from file instead of environment variable

- cluster/common.sh
- cluster/gce/util.sh
- cmd/haproxy-cfg-generator/data/haproxy.cfg.template
- cmd/haproxy-cfg-generator/data/sample_four_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_one_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_three_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_two_tp_haproxy.cfg
- test/kubemark/gce/util.sh
- test/kubemark/start-kubemark.sh
- test/kubemark/stop-kubemark.sh
>
> /kind bug
/kind design
> /kind flake
**What this PR does / why we need it**: Currently we use insecure port 8080 for all API communication in scaleout architecture. This PR does two things:
Secures the client ---- haproxy communication to use SSL with certificates generated by proxy as CA. (Intra-scaleout communication is still insecure after this PR. Yunwen will have a PR for that after integrating with this)
Cleanup several unnecessary and confusing intermediate kubeconfigs that are generated as part of scaleout cluster deployment.
Following …
> Use secure communication for client <--> proxy communication, cleanup unnecessary config files

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/manifests/etcd.manifest
- go.mod
refer to kubernetes PR https://github.com/kubernetes/kubernetes/pull/77561 and https://github.com/kubernetes/kubernetes/pull/77657
> /kind bug
when run arktos perf-test with these two env var: PROMETHEUS_SCRAPE_ETCD=true ENABLE_PROMETHEUS_SERVER=true to enable apiresponsiveness. But Prometheus failed to start with the error below when run clusterloader2
```
0/1 targets are ready, example not ready target: {map[endpoint:etcd-2382 instance:10.40.0.9:2382 job:master namespace:monitoring service:master] down}
```
arktos are missing the insecure http port number:2382 to access ETCD. This port 2382 is used …
> Use HTTPS as etcd-apiserver protocol when mTLS is enabled

- staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go
- test/e2e/arktos/multi_tenancy/test_suites/crd/test_system_share_crd.yaml
This PR fixed issue https://github.com/CentaurusInfra/arktos/issues/655: "Regular tenant does not get error when trying to delete a system forced-sharing CRD".
An e2e test case is added.
Verified in local env:
1. started a cluster via arktos-up.sh 
2. Created a tenant x and its admin context as follows:
```
ubuntu@ip-172-31-26-146:~/go/src/k8s.io/arktos$ kubectl create tenant x
setting storage cluster to 0
tenant/x created
ubuntu@ip-172-31-26-146:~/go/src/k8s.io/arktos$ hack/setup-multi-tenancy/setup_client.sh x admin
......
Context has been setup for tenant x/admin in /var/run/kubernetes/admin.kubeconfig.
......
```
3. Check the CRD networks.arktos.futurewei.com, which is created by arktos-up.sh in cluster bootstrap, is accessibel to the admin under tenant x.
``` …
```
> fix issue 655

- hack/arktos_cherrypick.sh
PLease add "CHERRY_PICK=true" before make update to enable this
>
Add hack/arktos_cherrypick.sh. it will add comments "File modified by cherrypick from Kubernetes on $(date +'%m/%d/%Y')" when PR is cherry-picked from community Kubernetes. 
```
hack/arktos_cherrypick.sh
```
Fixes #
```
Scenarios #1: File already exist in Arktos, modified by cherrypick
Existing:         Copyright 2016 The Kubernetes Authors.
New added:   Copyright 2020 Authors of Arktos - file modified.
Add cherrypick comments by …
```
> add hack/arktos_cherrypick.sh

- pkg/scheduler/factory/factory.go
- pkg/scheduler/scheduler.go
/kind feature
to enhance kube-scheduler with scheduling pods to all nodes across multiple RPs
Fixes #1013
POC code; no automated testing incurred.
expect to test together with other components later, probably in 1TP/2RP env.
NONE
> scheduler uses all nodes from multiple RPs in one big pool

- cmd/cloud-controller-manager/app/config/BUILD
- cmd/cloud-controller-manager/app/config/config.go
- cmd/cloud-controller-manager/app/core.go
- cmd/kube-controller-manager/app/BUILD
- cmd/kube-controller-manager/app/config/config.go
- cmd/kube-controller-manager/app/controllermanager.go
- cmd/kube-controller-manager/app/core.go
- cmd/kube-controller-manager/app/options/BUILD
- cmd/kube-controller-manager/app/options/options.go
- hack/lib/common.sh
- pkg/controller/cloud/node_controller.go
- pkg/controller/cloud/node_lifecycle_controller.go
- pkg/controller/service/BUILD
- pkg/controller/service/service_controller.go
- pkg/controller/volume/attachdetach/BUILD
- pkg/controller/volume/attachdetach/attach_detach_controller.go
- pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go
- pkg/controller/volume/persistentvolume/BUILD
- pkg/controller/volume/persistentvolume/pv_controller.go
- pkg/controller/volume/persistentvolume/pv_controller_base.go
- pkg/util/node/BUILD
- pkg/util/node/nodecache_utils.go
Please ignore the first 2 commits. They are reviewed in https://github.com/CentaurusInfra/arktos/pull/1011.
-- merged and removed.
Tests done:
In TP1:
ubuntu@ip-172-30-0-148:~/go/src/arktos$ cat /tmp/kube-controller-manager.log | grep "Caches are synced for " | grep node
I0309 22:12:36.434773     979 controller_utils.go:1089] Caches are synced for attach detach (w/o node) controller
I0309 22:12:36.504194     979 controller_utils.go:1089] Caches are synced for persistent volume (w/o node) controller
I0309 22:12:56.435835     979 nodecache_utils.go:90] Caches are synced for attach detach (node) controller
I0309 22:12:56.505039     979 nodecache_utils.go:90] Caches are synced for persistent volume (node) controller
. Note service controller is not started in local cluster up.
In RPs: …
> Multiple RPs support in KCM

- cmd/kubelet/app/BUILD
- cmd/kubelet/app/options/options.go
- cmd/kubelet/app/server.go
- docs/setup-guide/scale-out-local-dev-setup.md
- hack/arktos-up-scale-out-poc.sh
- hack/lib/common.sh
- pkg/controller/volume/attachdetach/attach_detach_controller.go
- pkg/scheduler/BUILD
- pkg/scheduler/eventhandlers.go
- pkg/scheduler/factory/factory.go
- pkg/scheduler/internal/cache/BUILD
- pkg/scheduler/internal/cache/debugger/BUILD
- pkg/util/node/BUILD
- staging/src/k8s.io/client-go/tools/cache/controller.go
> 1. Changed Kubelet TP config from ip:port pairs to kubeconfig files
Previous kubelet starts as 
root      1179  4.5  0.3 1261568 105304 pts/9  Sl+  00:48   0:00 /home/ubuntu/go/src/arktos/_output/bin/hyperkube kubelet --v=3 --vmodule= --chaos-chance=0.0 --container-runtime=remote --hostname-override=ip-172-30-0-122 --cloud-provider= --cloud-config= --address=0.0.0.0 --kubeconfig /var/run/kubernetes/kubelet.kubeconfig --feature-gates=AllAlpha=false,WorkloadInfoDefaulting=true --cpu-cfs-quota=true --enable-controller-attach-detach=true --cgroups-per-qos=true --cgroup-driver= --cgroup-root= --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5% --eviction-soft= --eviction-pressure-transition-period=1m --pod-manifest-path=/var/run/kubernetes/static-pods …
> Use kubeconfig to replace TP api server endpoints in kubelet

- cmd/kube-controller-manager/app/core.go
- hack/arktos-up-scale-out-poc.sh
- hack/lib/common-var-init.sh
- pkg/controller/podgc/gc_controller.go
This change fix this issue: https://github.com/CentaurusInfra/arktos/issues/1020
Before code fix, GC list nodes every 20s and could not find node, hence recycle pods every 20s.
```
ubuntu@ip-172-30-0-148:~$ kubectl get pods -A
NAMESPACE     NAME                                HASHKEY               READY   STATUS    RESTARTS   AGE
default       nginx-deployment-676f445fdf-t2lnw   5880710705033174106   1/1     Running   0          55s
kube-system   kube-dns-6fdcc959b4-66ssw           1357571739321344899   2/3     Running   1          110s
```
After stopped node where pod t2lnw was created, it got recreated in a different host:
```
ubuntu@ip-172-30-0-148:~$ kubectl get pods -A
NAMESPACE     NAME                                HASHKEY               READY   STATUS    RESTARTS   AGE
default …
```
> Fix pod GC issue in scale out case

- staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
Fixing https://github.com/CentaurusInfra/arktos/issues
Verified with a successful 100-node scale-out 1TP-1RP density test run, where the maximal number of pods should be 3000+. Here is the Prometheus graph for metric etcd_object_count of pods, where the peak number reaches 3430.
> Fix issue 1023

- perf-tests/clusterloader2/cmd/clusterloader.go
- perf-tests/clusterloader2/pkg/config/cluster.go
this PR targets 430 POC.
/kind feature
It introduces to perf command tool (clusterloader) a new env var controlling whether to access RPs to list nodes, or not.
In default mode (no chaos monkey), clusterloader does not really care much about node details, other than the number of nodes. This PR makes option for it not to access RPs, so to access TP directly, w/o proxy.
When no to access RPs, chaos monkey must not be enabled (it is disabled by default). The change to support enabling chaos monkey will be considered later (as chaos monley is not being used in current stage of Arktos scalability test)
Yes
```release-note
run-e2e.sh could …
```
> perftest tool: bypass accessing RPs

- pkg/controller/podgc/gc_controller.go
__This PR goes to POC 430 branch only.__
/kind bug
GC controller, as part of kube-controller-manager, list nodes, and delete pods if their nodes are gone. In scale-out env, GCC currently list nodes from RPs only; for static pods run from TP itself, it considers them as garbage and recycles them.
This PR changes GCC to include its own TP as one of the node sources.
Fixes #1042
NONE
> bug fix: static pods are constantly recycled

- perf-tests/clusterloader2/testing/experiments/enable_daemonset.yaml
- perf-tests/clusterloader2/testing/load/config.yaml
Add "ENABLE_DAEMONSET" to perf-test load testing and set default to false 
Fixes #
**Special notes for your reviewer**
1tp-1rp for 100 nodes perf testing run successfully with the configuration below:
```
export KUBEMARK_NUM_NODES=100 NUM_NODES=2 SCALEOUT_TP_COUNT=1 RUN_PREFIX=disableds-032521-1x100
export MASTER_DISK_SIZE=200GB MASTER_ROOT_DISK_SIZE=200GB KUBE_GCE_ZONE=us-central1-b MASTER_SIZE=n1-highmem-32 NODE_SIZE=n1-highmem-16 NODE_DISK_SIZE=200GB GOPATH=$HOME/go KUBE_GCE_ENABLE_IP_ALIASES=true KUBE_GCE_PRIVATE_CLUSTER=true CREATE_CUSTOM_NETWORK=true KUBE_GCE_INSTANCE_PREFIX=${RUN_PREFIX} KUBE_GCE_NETWORK=${RUN_PREFIX} ENABLE_KCM_LEADER_ELECT=false …
```
> Disable Daemonset from perf-test: load testing

- cmd/haproxy-cfg-generator/cfg_generator.go
- cmd/haproxy-cfg-generator/data/sample_four_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_one_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_three_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_two_tp_haproxy.cfg
> /kind bug
the haproxy service periodically performs health check with the backend API servers. the current configuration for this backend health check is check-ssl, which enforces full TSL traffic for the check. this causes a lot log entries in the api server due to the source where the health check originated is not the 443 port of the haporxy.
currently one can either specify the "source <proxy server Ip>:443" or just perform TCP checks to backend servers. this PR takes the later one to not occupy the 443 port too much just in case to affect testing throughputs.
Fixes #1048 
Tested with 100 node under  POC 430 branch.
> bug fix 1048: api server tsl handshake error with proxy server

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/partitionserver-configure-helper.sh
> /kind bug
rp server failed to collect pprof becuase there is no kube-scheduler running. Add component running judgment, only collecting pprof for running component.
Fixes #https://github.com/CentaurusInfra/arktos/issues/1057
```release-note
```
> fix rp server failed to collect pprof error

- cluster/gce/gci/configure-helper-common.sh
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
> /kind bug
Fix issue #1039 and #1046
Fixes #1039 #1046 
500 nodes run for 1tp*1rp passed for both load and density using this build: https://github.com/futurewei-cloud/arktos-perftest/commits/perf-20210326. 
Logs can be found under GCP project: workload-controller-manager on sonyadev4: /home/sonyali/logs/perf-test/gce-500/arktos/fix1038-032621-1x1x500
500 nodes run for 2tp*1rp passed for both load and density using this build: https://github.com/futurewei-cloud/arktos-perftest/commits/perf-20210330. 
Logs can be found under GCP project: workload-controller-manager on sonya-uswest2: /home/sonyali/logs/perf-test/gce-500/arktos/perf033021-2x1x500
**Does …
> Fix issue #1039 and #1046

- pkg/scheduler/algorithm/predicates/metadata.go
- pkg/scheduler/algorithm/priorities/interpod_affinity.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/eventhandlers.go
- pkg/scheduler/internal/cache/cache.go
- pkg/scheduler/internal/queue/scheduling_queue.go
- pkg/scheduler/scheduler.go
Add some debug logs for perf analysis
Fixes #
```release-note
```
```
I0408 17:40:19.912410       1 eventhandlers.go:164] Getting pod latency-deployment-306-8566f7d674-4dftj from API server
I0408 17:40:19.912478       1 scheduling_queue.go:210] adding pod arktos/y0g937-testns/latency-deployment-306-8566f7d674-4dftj to the scheduling queue.
I0408 17:40:19.912514       1 scheduling_queue.go:819] About to try and schedule pod arktos/y0g937-testns/latency-deployment-306-8566f7d674-4dftj
I0408 17:40:19.912525       1 scheduler.go:458] Attempting to schedule pod: arktos/y0g937-testns/latency-deployment-306-8566f7d674-4dftj
I0408 …
```
> debug logging for scheduler perf analysis

- pkg/scheduler/core/generic_scheduler.go
K8s document said percentageOfNodesToScore can be set as lower than 5%. But the code seems only accept 5% as lowest threshold. Adding log to confirm.
> Add log for percentageOfNodesToScore vs. evaluated node

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
- test/kubemark/start-kubemark.sh
> /kind bug
fix bug in KCM on TP cluster to talk to the proxy instead of pointing to the local cluster --- the RP directly connect from KCM on TP is not yet supported in main -- it is currently tested in 430 branch
Fixes #1038 
unblock perf testing in master branch. essential changes is 
```
if [[ "${KUBERNETES_TENANT_PARTITION:-false}" == "true" ]]; then
create-kubeconfig "kube-controller-manager" ${KUBE_CONTROLLER_MANAGER_TOKEN} "${PROXY_RESERVED_IP}" "443" "https"
```
none 
**Testing:
1. 1 TP, 1 RP scaleout
2. scaleup test
verified bug fix:
```
ybai2016@yb01-multiple-rp-kubemark-tp-1-master /var/log …
```
> fix issue 1038. kubeconfig for kcm on TP to use the proxy till the KCM supports direct talk to RPs

- pkg/scheduler/algorithm/predicates/metadata.go
- pkg/scheduler/algorithm/predicates/metadata_test.go
- pkg/scheduler/algorithm/predicates/predicates.go
- pkg/scheduler/algorithm/predicates/testing_helper.go
- pkg/scheduler/core/generic_scheduler.go
__targeting 430 POC for now__
> /kind feature (back-port from upstream k8s)
This PR is based on [k8s PR#86046](https://github.com/kubernetes/kubernetes/pull/86046): 
Optimize required pod affinity
Based on the original author, 86046 was able to improve performance about 2-4x
this is the one of series PRs kube-scheduler related performance related improvements (up to k8s 1.18.5). It will be put out of POC branch until it is perf tested with others in the series. While it is marked as WIP, peer comments are welcome; just not to merge yet.
The code was manually modified based on upstream PR, not automatically cherry-picked, due to the conflicts it would have caused. Unit test code is not …
> kube-sched: perf-related back-ports: Merge pull request #86046 from ahg-g/ahg1-affinity

- pkg/scheduler/algorithm/predicates/metadata.go
- pkg/scheduler/api/types.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/core/generic_scheduler_test.go
__targeting 430 POC for now__
/kind feature (back-port from upstream k8s)
including 3 k8s PRs that are perf optimization related
1. [k8s PR80533 Query nodes in Schedule only when there are no predicates](https://github.com/kubernetes/kubernetes/pull/80533)
1. [k8s PR85030 Set default percentageOfNodesToScore in kube-scheduler back to "adaptive"](https://github.com/kubernetes/kubernetes/pull/85030)
1. [k8s PR81346 Add fast path to podFitsOnNode](https://github.com/kubernetes/kubernetes/pull/81346)
this is the one of series PRs kube-scheduler related performance related improvements (up to k8s 1.18.5). It will be put out of POC branch until it is perf tested with others in the series. …
> kube-sched: perf-related back-ports: adopt PR 80533 85030 81346

- cluster/gce/gci/configure-helper-common.sh
> /kind bug
> prometheus metric for the Arktos proxy is not picked up by the cluster api servers. this is a missing code in 330 code merged and fixed in 530 perf branch. Now merge the fix to master.
Fixes #
None
> fix prometheus config to include haproxy metrics

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
- cluster/proxy-down.sh
- cluster/proxy-up.sh
- cluster/skeleton/util.sh
- test/kubemark/gce/util.sh
- test/kubemark/start-kubemark.sh
- test/kubemark/stop-kubemark.sh
Currently in Arktos scalability test setup, the proxy were created and then updated per RP or TP cluster creation, which is not efficient in setup the test env.
This PR decouples the proxy creation routines from the cluster master setup functions and only create the proxy once all RP/TPs were setup to optimize the proxy creation time for multiple RP/TP env.
Fixes #
None
> Decouple proxy operations from kube-up and create-master functions and optimize proxy creation routines

- perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
- pkg/controller/job/job_controller.go
test done: arktos-up.sh got log:
I0618 22:09:22.827344   19367 job_controller.go:266] pod system/kube-system/virtlet-sfwpm, pod_startup 2827 ms, runToWatch 827 ms, runTime 2021-06-18T22:09:22Z, watchTime 2021-06-18T22:09:22.827331234Z
> Add perf log to perf test and controller manager

- cmd/kubemark/hollow-node.go
- perf-tests/clusterloader2/pkg/framework/multiclient.go
Explicitly set user agent for the hollow node and the perf-test client so that in log and in prometheus they can be differentiated for perf analysis.
> set user agent for hollow nodes and perf test clients

- cmd/kube-scheduler/app/options/options.go
Before fix, debug log:
```
I0716 19:08:32.737344   31665 options.go:383] === kubeConfigs address 0xc000401dc0, user agent []
I0716 19:08:32.738162   31665 options.go:385] === kubeConfigs user agent [hyperkube/v0.7.0 (linux/amd64) kubernetes/$Format/scheduler]
I0716 19:08:32.738180   31665 options.go:392] === restConfigs address 0xc0009ab8c0, user agent [hyperkube/v0.7.0 (linux/amd64) kubernetes/$Format/scheduler]
I0716 19:08:32.738519   31665 options.go:397] === restConfigs user agent [hyperkube/v0.7.0 (linux/amd64) kubernetes/$Format/leader-election]
I0716 19:08:32.738538   31665 options.go:402] === kubeConfigs address 0xc000401dc0, user agent [hyperkube/v0.7.0 (linux/amd64) kubernetes/$Format/leader-election]
```
After fix, debug log:
```
I0716 21:01:36.171693   18541 options.go:383] …
```
> Fix a bug that event client was created with wrong user agent

- cmd/kube-controller-manager/app/controllermanager.go
/kind bug
This PR fixes the error that was observed during perf test:
```
E0729 19:49:16.787146    8872 wait_for_pods.go:85] WaitForControlledPodsRunning: namespace(ixkj3v-testns), labelSelector(name=saturation-deployment-0): 11 pods disappeared: saturation-deployment-0-866fd6bb84-tlzdt, saturation-deployment-0-866fd6bb84-9hb5w, saturation-deployment-0-866fd6bb84-n9v6b, saturation-deployment-0-866fd6bb84-zh66w, saturation-deployment-0-866fd6bb84-thpcf, saturation-deployment-0-866fd6bb84-ndmgg, saturation-deployment-0-866fd6bb84-xtqt2, saturation-deployment-0-866fd6bb84-svrzm, saturation-deployment-0-866fd6bb84-r29wm, saturation-deployment-0-866fd6bb84-wcnfk, saturation-deployment-0-866fd6bb84-rcdp2
```
The root cause is …
> bug fix: gc controller deletes pods as it cannot access node resources

- pkg/registry/cachesize/cachesize.go
> PR 96117 - Disable watchcache for events 1.18

- cmd/kube-controller-manager/app/core.go
- pkg/controller/nodelifecycle/node_lifecycle_controller.go
- pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
- pkg/controller/nodelifecycle/scheduler/BUILD
- pkg/controller/nodelifecycle/scheduler/taint_manager.go
- pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
- pkg/controller/util/node/controller_utils.go
- test/integration/scheduler/taint_test.go
Reduced # of list pods requests to ETCD. 1 request per 3 second, 1 call per node. This change significantly reduced system load during large cluster density test.
> Use watch instead of list pods in node controller

- staging/src/k8s.io/client-go/tools/cache/reflector.go
- staging/src/k8s.io/client-go/tools/cache/shared_informer.go
Currently scheduler and kubelet both has watch never expire. I don't see why KCM should have watch expire every few minutes and re-establish the watch connection. Trying a short cut to see whether this improve latency.
```
kubelet-hollow-node-1-zw2xm.log-20210804-1628035208.gz:I0803 18:47:52.727101       6 reflector.go:218] Starting reflector *v1.Secret (0s) from object-"arktos"/"nkrldp-testns"/"default-token-pkvvr"
kubelet-hollow-node-1-z6jm9.log-20210804-1628035208.gz:I0803 20:44:45.766528       6 reflector.go:218] Starting reflector *v1.Secret (0s) from object-"arktos"/"sc2tap-testns"/"default-token-qsnq5"
kubelet-hollow-node-1-zw2xm.log-20210804-1628035208.gz:I0803 17:04:19.057921       6 reflector.go:218] Starting reflector *v1.Action (0s) from …
```
> Set watch never expire

- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_node_status.go
Same as PR 835 except test not ported.
Tested on 1TP/1RP 100 node cluster.
. Before change, get node request 17849, patch node request 1499. After change, get node request 303, patch node request 1100
. Depends on when log was pulled, total # of requests might variant. Using patch node request # as an example, get node still reduced a lot.
. There is no non 200 get/patch node requests in audit log.
25K run on 8/3 has 66M get and 4.5M patch. Total request in RP 142M.
> Reduce kubelet getting node requests.

- cmd/kube-apiserver/app/server.go
- staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
- staging/src/k8s.io/client-go/tools/cache/reflector.go
From audit log, there seems a problem when watch is longer than 10 min.
```
/home/sonyali/logs/perf-test/gce-25k/arktos/poc930-081621-1x1x25k/log_density/kubemark_tp_1_master/log$zgrep "\"verb\":\"watch\"" kube-apiserver-audit.log* | grep pods | grep -v "\"userAgent\":\"kubemark" | grep latency-deployment > ~/perf-log/2021-08-16/watch-latency-deployment.pods.audit.log
/home/sonyali/logs/perf-test/gce-25k/arktos/poc930-081621-1x1x25k/log_density/kubemark_tp_1_master/log$ cat ~/perf-log/2021-08-16/watch-latency-deployment.pods.audit.log | grep latency-deployment-39 | grep 098x36-testns
kube-apiserver-audit.log-20210816-1629152119.gz:{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"a5bd7ddd-a728-4062-9a2a-9030a63abb42","stage":"ResponseStarted","requestURI":"/api/v1 …
```
> Add trace for resync, revert watch timeout changes

- perf-tests/clusterloader2/pkg/measurement/common/scheduling_throughput.go
- perf-tests/clusterloader2/pkg/measurement/util/object_store.go
- perf-tests/clusterloader2/pkg/measurement/util/wait_for_pods.go
Trying avoid excessive list pods from API server during test. Reason: during density test, at the latency pod creation period, each latency pod is created by one deployment. Perf test create pod store for every single deployment and hence caused excessive list pods requests to API server. This may be the reason that perf test has pod start up latency spike every 10-15 seconds.
This change try to reuse pod store across multiple deployments. Pod store list/watch all latency pods, filter out pods that does not belong to current deployment at client side.
This is a preliminary change. Improvements might needed:
1. Scan over all pods at local store might added a lot of time. Need to compare with KCM pod start up latency to see whether additional local index for label selector might need to be …
> Reduce perf test list all pods from API server cache

- perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
- test/e2e/framework/perf_util.go
add "create_to_run" to pod latency report
Fixes #
verified with poc930 code using 100 nodes. Results looks good:
PodStartupLatency
```
{
"data": {
"Perc50": 1000,
"Perc90": 1000,
"Perc99": 1000
},
"unit": "ms",
"labels": {
"Metric": "create_to_run"
}
},
```
SaturationPodStartupLatency
```
{
"data": {
"Perc50": 1000,
"Perc90": 2000,
"Perc99": 4000
},
"unit": "ms",
"labels": {
"Metric": "create_to_run"
}
},
```
```release-note
```
> Add "create_to_run" to pod latency

- perf-tests/clusterloader2/pkg/imagepreload/imagepreload.go
- perf-tests/clusterloader2/pkg/measurement/common/service_creation_latency.go
- perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
- perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
- perf-tests/clusterloader2/pkg/measurement/util/selector.go
porting community PRs:
PR 1780: Migrate NewInformer to cache.ListerWatcher
PR 1855 Add channel for events to PodStartupLatency
Tested with 100 node perf run and passed.
> port community perf test PRs

- cmd/kube-controller-manager/app/config/config.go
- cmd/kube-controller-manager/app/controllermanager.go
- cmd/kube-controller-manager/app/core.go
- cmd/kube-controller-manager/app/options/options.go
- cmd/kube-scheduler/app/options/options.go
- cmd/kubelet/app/server.go
- cmd/kubemark/hollow-node.go
- pkg/controller/util/node/controller_utils.go
- staging/src/k8s.io/client-go/util/clientutil/clientutil.go
- staging/src/k8s.io/client-go/util/clientutil/clientutil_test.go
fix scale out client identity
This fix fill in correct user agent for rest client when components need to talk to API server in another cluster.
> Set user agent for clients when talking to api servers in the partition

- staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
The first commit helps use to understand the size of channel.
The second commit send fake bookmark event to client to reduce size of initEvents. When reflector get bookmark event, it only update resource version, it will not process event. This shall greatly reduce the size of init pod events in case of large size cluster. 
In 100 node cluster. Did not run perf test.
One watch for action/pod/ per node
```
I0910 22:34:40.596881       1 cacher.go:495] Channel size 10, objectType *core.Pod, key [/pods], RV [375], indexedTrigger [0xc00060e440], triggerSupported [true], pred field [spec.nodeName=hollow-node-1-hlz7f], watcher [0xc014037b90]
I0910 22:34:40.582618       1 cacher.go:495] Channel size 10, objectType *core.Action, key [/actions], RV [1], indexedTrigger [0xc001032520], …
```
> Send fake bookmark event to client to reduce size of initEvents

- hack/arktos-up-scale-out-poc.sh
- hack/lib/common.sh
/kind feature
This PR automatically helps to set up local dev  1 X 1 scale-out cluster by adding the following three automation steps:
- Automatically install Arktos network controller on TP node,
- Automatically set podCIDR on RP node,
- Automatically install flannel cni on RP node. Before daemonset is fully supported by Arktos, the simple daemonset-based flannel installation is not an option. As a work around, flanneld is installed and running as process on RP node.
Fixes # 1189
this PR depends on following PRs in queue:
#1181
#1190
#1191
The step "Set up environment variables" for TP setup and RP setup in …
> Issue#1189: changes in arktos-up-scale-out-poc.sh for automation of local dev 1X1 scale-out setup

- hack/lib/common-var-init.sh
/kind bug
This PR identify the available resolv.conf on Ubuntu 16.04 and use it in arktos cluster start up process; If no available file can be identified, it uses env var UPSTREAM_DNS_IP to compose a minimum resolv.conf; if that var is not provided, it falls back to the well known public DNS server 8.8.8.8. 
Fixes #1196
NONE
> ensure resolv.conf for Ubuntu 16.04

- cmd/kubelet/app/server.go
/kind bug
This maintains the prior behavior of the kubelet when the cgroup setup is unsupported. It emits an error rather than exiting. This is important for those who run kubelets locally to test changes unrelated to monitoring or cgroup setup.
Fixes #1219 
this fix is port of  upstream k8s PR https://github.com/kubernetes/kubernetes/pull/79245
NONE
> kunsupported cgroup setup causes kubelet to emit a warning rather than existing

- hack/arktos-up.sh
/kind bug
Write config to stop running of mizar kopf when cluster is arktos.
Mizar depends on such config to decide whether the cluster is arktos or k8s. So the config needs to be written to let mizar know it's arktos.
Current mizar controllers and kopf are both running which is unexpected. 
NONE
> write config to stop running of mizar kopf when cluster is arktos

- cmd/kube-controller-manager/app/mizarcontrollers.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
I1203 02:10:06.131962    4922 mizar-arktos-network-controller.go:162] Mizar-Arktos-Network-controller - get network: &v1.Network{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"default", GenerateName:"", Tenant:"system", Namespace:"", SelfLink:"/apis/arktos.futurewei.com/v1/networks/default", UID:"1d246f89-6f12-4d6c-ba90-94570390a704", HashKey:6021324579093697607, ResourceVersion:"347", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63774094202, loc:(*time.Location)(0x99f8840)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), …
> Bug fix for mizar-arktos network controller watch/update arktos network objects

- hack/arktos-worker-up.sh
Run worker up for arktos up with Mizar (aws):
1. Set up dev host with https://github.com/q131172019/arktos/blob/CarlXie_singleNodeArktosCluster/docs/setup-guide/single-node-dev-scale-up-cluster-with-Mizar.md
2. Start master node with Mizar
3. Copy /var/run/kubernetes/client-ca.crt from master to worker
4. Start worker with Mizar: 
```
API_HOST=<master node name:-ip-172-30-0-14> CNIPLUGIN=mizar ./hack/arktos-worker-up.sh
```
Tested with 1 master and 3 workers
> Simplify worker up

- cmd/kube-proxy/app/server.go
- pkg/kubemark/hollow_proxy.go
- pkg/proxy/config/api_test.go
- pkg/proxy/config/config.go
- pkg/proxy/config/config_test.go
- pkg/proxy/endpoints.go
- pkg/proxy/endpoints_test.go
- pkg/proxy/healthcheck/healthcheck.go
- pkg/proxy/healthcheck/healthcheck_test.go
- pkg/proxy/iptables/proxier.go
- pkg/proxy/iptables/proxier_test.go
- pkg/proxy/ipvs/proxier.go
- pkg/proxy/ipvs/proxier_test.go
- pkg/proxy/service.go
- pkg/proxy/service_test.go
- pkg/proxy/types.go
- pkg/proxy/userspace/proxier.go
- pkg/proxy/userspace/proxier_test.go
- pkg/proxy/userspace/roundrobin.go
- pkg/proxy/userspace/roundrobin_test.go
- pkg/proxy/util/utils.go
- pkg/proxy/util/utils_test.go
- pkg/proxy/winuserspace/proxier.go
- pkg/proxy/winuserspace/proxier_test.go
- pkg/proxy/winuserspace/proxysocket.go
- pkg/proxy/winuserspace/roundrobin.go
- pkg/proxy/winuserspace/roundrobin_test.go
- pkg/proxy/winuserspace/types.go
- staging/src/k8s.io/apimachinery/pkg/types/namespacedname.go
Tested with PR 1244 with 2TP1RP.
Deployed a whoami service in both TP, deployed another pod in both TP for curling purpose. All pods are in system tenant. Was able to curl service endpoint and get back correct whoami container id.
```
---
apiVersion: v1
kind: Service
metadata:
name: whoami-service
namespace: default
spec:
selector:
app: whoami
ports:
- protocol: TCP
port: 8000
targetPort: 80
---
apiVersion: apps/v1 
kind: Deployment
metadata:
name: whoami-deployment
spec:
replicas: 2
selector:
matchLabels:
app: whoami
template:
metadata:
labels:
app: whoami
spec:
containers:
- image: ctmagazin/whoami 
name: whoami-container
ports:
- containerPort: 8000
```
> Kube proxy multi tenant scaleout

- pkg/registry/core/pod/storage/BUILD
- pkg/registry/core/pod/storage/storage.go
- staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
- staging/src/k8s.io/apiserver/pkg/endpoints/request/context.go
Explicitly uses the information set in the handler to retrieve the pod name in the Action handlers. The default context with requestInfo is changed since golang 1.39.
VM action is currently broken in Arktos since golang 1.39 upgrade in PR #921 
Fixes #1251 
None
**Local testing of the fix:
```
root@ip-172-31-10-115:/work/src/k8s.io/kubernetes# kubectl get pods -AT
TENANT   NAMESPACE     NAME                              HASHKEY               READY   STATUS    RESTARTS   AGE
system   default       vmdefault                         2682661623882133849   1/1     Running   0          3s
system …
```
> Use explicitly set request context in action creation

- hack/arktos-up-scale-out-poc.sh
What type of PR is this?
/kind bug
What this PR does / why we need it:
Write config to stop running of mizar kopf when cluster is arktos and it's in roll-out mode. The same thing has been done for arktos-up.sh via https://github.com/CentaurusInfra/arktos/pull/1235. It needs to be done for file hack/arktos-up-scale-out-poc.sh.
Mizar depends on such config to decide whether the cluster is arktos or k8s. So the config needs to be written to let mizar know it's arktos.
Which issue(s) this PR fixes:
In Arktos roll-out, current mizar controllers and kopf are both running which is unexpected.
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
NONE
> in arktos-up-scale-out-poc.sh, write config to stop running of mizar kopf when cluster is arktos

- staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/flavors.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/images.go
Added /flavors and /images PATH and the GET handlers.
local testing:
```
root@ip-172-31-10-115:/work/src/k8s.io/kubernetes# curl http://localhost:8080/images -v | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /images HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache, private
< Date: Fri, 07 Jan 2022 23:26:48 GMT
< Content-Length: 244
< Content-Type: text/plain; charset=utf-8
< 
{ [244 bytes data]
100   244  100   244    0     0   238k      0 --:--:-- --:--:-- --:--:-- …
```
> openstack essential flavors and images support for VM creations -- part2

- cluster/gce/util.sh
- cluster/kube-up.sh
/kind bug
This PR only registers network CRD at all TPs in kube-up scale-out, not in kubemark scale-out.
There was a regression introduced by #1278, which registers network CRD during scale-out start up process. For perf test, start-kubemark will hit the code and could not find the kubeconfig files named for kube-up scale-out TPs. The fix is NOT to register this CRD for kubemark, as kubemark does not really need such for testing.
Fixes #1280
```release-note
NONE
```
> register network crd only for kube-up, not for kubemark

- pkg/controller/mizar/mizar-arktos-network-controller.go
- pkg/controller/mizar/mizar-pod-controller.go
- pkg/controller/mizar/mizar-service-controller.go
Fix issue https://github.com/CentaurusInfra/arktos/issues/1293.
. Before fix:
```
ubuntu@ip-172-30-0-14:~/go/src/k8s.io/arktos$ ./cluster/kubectl.sh get pods -AT -o wide
TENANT   NAMESPACE     NAME                               HASHKEY               READY   STATUS              RESTARTS   AGE    IP            NODE             NOMINATED NODE   READINESS GATES
aaa      kube-system   coredns-default-65df55d94b-ktptj   8781758764375017681   0/1     ContainerCreating   0          58s    <none>        ip-172-30-0-14   <none>           <none>
system   default       mizar-daemon-dvv86                 8954631230949460177   1/1     Running             0          3m4s   172.30.0.14   ip-172-30-0-14   <none>           <none>
system   default       mizar-operator-5c97f7478d-gdpqb    7393075030848523141 …
```
> Bug fix: add pod creation event back to queue when network is not ready

- pkg/controller/mizar/mizar-pod-controller.go
This fix issue https://github.com/CentaurusInfra/arktos/issues/1285
. This change keeps that original implementation that pod created w/o mizar vpc/subnet annotation to be attached to default tenant network.
. It also allows pod created with mizar annotation to be attached to the designated vpc/subnet.
. It is also possible to update mizar annotation so that the pod can be moved across different vpc/subnet - mizar is having issue to support this. see https://github.com/CentaurusInfra/arktos/issues/1286
```
ubuntu@ip-172-30-0-14:~/go/src/k8s.io/arktos$ ./cluster/kubectl.sh get pods -AT -o wide
TENANT   NAMESPACE     NAME                               HASHKEY               READY   STATUS              RESTARTS   AGE   IP            NODE             NOMINATED NODE   READINESS GATES
aaa …
```
> Assign pod to default mizar network only when Mizar VPC/subnet annotation is not present in pod

- staging/src/k8s.io/apiserver/pkg/util/openstack/BUILD
- staging/src/k8s.io/apiserver/pkg/util/openstack/flavors.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/images.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/types.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/types_test.go
This will be first quality effort for 130. slight refactor types and utils files and essential UT test fixes. all new UTs are passing now.
Local testing:
```
yunwens-mbp:kubernetes yunwenbai$ bazel test //staging/src/k8s.io/apiserver/pkg/util/openstack/...
INFO: Analyzed 4 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets and 1 test target...
INFO: Elapsed time: 0.297s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
//staging/src/k8s.io/apiserver/pkg/util/openstack:go_default_test (cached) PASSED in 0.3s
Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 1 total action
yunwens-mbp:kubernetes yunwenbai$ bazel test //staging/src/k8s.io/apiserver/pkg/util/...
INFO: Analyzed 33 targets (0 packages …
```
> Slight refactor and essential UT

- cluster/common.sh
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/configure.sh
- cluster/gce/gci/master-helper.sh
- cluster/gce/gci/scaleoutserver-helper.sh
- cluster/gce/manifests/kube-controller-manager.manifest
- cluster/gce/util.sh
/kind bug
/kind feature
The PR is to ensure to automatically create the network object (flat or mizar) of "default"  for system tenant when scale out 1 x 1 cluster or scale-up cluster of KUBE-UP environment.
If network support is not desired, setting env var DISABLE_NETWORK_SERVICE_SUPPORT will disable this feature.
Fixes # 1279
TEST:
NOTE:  Must unset the environment variables below before start cluster to do tests.
1. For mizar to start kube-up cluster:
start cluster:
```
unset KUBE_GCE_MASTER_PROJECT KUBE_GCE_NODE_PROJECT KUBE_GCI_VERSION  KUBE_GCE_MASTER_IMAGE  KUBE_GCE_NODE_IMAGE …
```
> [kube-up][scale-out]Automatically create default network object (flat or mizar) of for system tenant

- pkg/controller/mizar/mizar-pod-controller.go
- staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/types.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/types_test.go
- test/e2e/arktos/testvm.json
Local testing:
```
root@ip-172-31-10-115:/work/src/k8s.io/kubernetes# curl -L -k -XPOST -H "Content-Type: application/json" -H "User-Agent: kubectl/v0.9.0 (linux/amd64) kubernetes/$Format" -H "Accept: application/json" -H "openstack: true" 'http://localhost:8080/servers' -d @test/e2e/arktos/testvm.json -v | jq
Note: Unnecessary use of -X or --request, POST is already inferred.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /servers HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: kubectl/v0.9.0 (linux/amd64) …
```
> ServerType update to fit Openstack required and key optional configs.

- staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/BUILD
- staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
- staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/types.go
- test/e2e/arktos/testvm-batch.json
local test:
```
root@ip-172-31-10-115:/work/src/k8s.io/kubernetes# curl -L -k -XGET -H "Content-Type: application/json" -H "User-Agent: kubectl/v0.9.0 (linux/amd64) kubernetes/$Format" -H "Accept: application/json" -H "openstack: true" 'http://localhost:8080/servers' -d @test/e2e/arktos/testvm-list.json -v | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /servers HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: kubectl/v0.9.0 (linux/amd64) kubernetes/
> Accept: application/json
> openstack: true
> …
```
> Filter Openstack request related VMs in list and basic error handling 

- hack/arktos-up-scale-out-poc.sh
- hack/arktos-up.sh
- hack/lib/common.sh
When starting up arktos cluster, if cni plugin is Mizar, there need some time for Mizar to be in "Provisioned" state which indicate Mizar is ready.
This pr is to add a waiting until Mizar is ready.
/kind feature
1. For the newly added func kube::common::wait-until-mizar-ready, it's copied from existing code in cluster/gce/ubuntu/configure-helper-common.sh line 3291 function wait-until-mizar-ready. 
I was considering using the same func there but from its location it's not proper to use it. 
I'm opening to suggestion from reviewer on how the functions shall be organized.
2. We need to do the same thing …
> Wait mizar ready when starting up local cluster

- cluster/gce/gci/configure-helper.sh
/kind bug
This PR sets --resource-name-salt arg value which does not violate DNS naming check.
Current value is of form of TP server ip, which could not pass the DNS name validation.
Fixes #1318
tested on 1tp+1rpx1worker cluster
```
$ kubectl get rs -n kube-system | grep coredns-default
coredns-default-hwc-kubeup-test-tp-1-7456994c79   3444567537333564004   1         1         0       28m
```
```release-note
NONE
```
> arktos network controller arg --resource-name-salt  set valid value in kube-up scale-out cluster

- cluster/common.sh
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/configure.sh
- cluster/gce/gci/master-helper.sh
- cluster/gce/gci/scaleoutserver-helper.sh
- cluster/gce/manifests/kube-controller-manager.manifest
- cluster/gce/util.sh
- cmd/BUILD
- cmd/kube-controller-manager/app/mizarcontrollers.go
/kind bug
/kind cleanup
/kind feature
The PR is to enable the feature - automatically create the default mizar VPC and Subnets objects for all tenants including system tenant and non-system tenants after scale out 1 x 1 cluster or scale-up cluster of KUBE-UP environment starts.
System tenant: 
``` 
vpc - system-default-network 
subnet - system-default-network-subnet
```
Non-system tenant: 
```
vpc - {{tenant name}}-default-network
subnet - {{tenant name}}-default-network-subnet 
```
If network support is not desired, setting environment variable DISABLE_NETWORK_SERVICE_SUPPORT to true will disable this feature; in the meantime, if NETWORK_PROVIDER is set to 'mizar', the vpc 'vpc0' and subnet 'net0' are still …
> [kube-up][scale-out]Automatically create default mizar vpc and subnet for tenants 

- cluster/gce/gci/configure-helper-common.sh
/kind bug
This PR sets resolv-conf arg of non-loop upstream DNS for kubelet, so to break the DNS looping found in coredns pods.
Fixes #1300
With this fix, the DNS loop is broken, but coredns may still suffer other issues, which will be coped with by separate tickets.
```release-note
NONE
```
> kube-up kubelet uses real DNS upstream server for systemd-enabled Ubuntu

- hack/arktos-up-scale-out-poc.sh
Features:
. Deploy mizar operator on tp master
. Start kube-proxy and kubelet on TP master
. Use mizar templates saved in third-party folder
. Do not start daemonset from non primary TP
Test done:
1. Verified kube proxy and kubelet running on tp master only connects to tp master
2. Verified previous start up setting can start 1x1 scale out cluster
Instruction to start non primary TP:
```
export IS_SECONDARY_TP=true
```
> Make local scale out have same architecture as kube up

- cmd/kube-controller-manager/app/mizarcontrollers.go
- hack/arktos-up-scale-out-poc.sh
- pkg/controller/mizar/mizar-node-controller.go
- third_party/mizar/mizar-daemon-tpmaster.yaml
1. Deploy daemon to TP master.
2. Add TP master node(s) into mizar droplets
Currently test passed in 1x1 local dev env. But 2x2 test is missing mizar eps for hosts. Will need mizar team to take a look.
In 1x1 scaleout, if kube-dns and coredns pod can be created successfully (Issue https://github.com/CentaurusInfra/arktos/issues/1357 tracks the pod creation issue), mizar host endpoints can be created, kube-dns&coredns pods runs w/o crashing, service endpoints filled in correctly)
> Add TP master into mizar droplets

- hack/arktos-up-scale-out-poc.sh
- hack/lib/common-var-init.sh
/kind bug
This PR is to ensure the directory /etc/kubernetes will be automatically created on scale-out TP servers if the directory is not existing as default. This will ensure to start mizar-operator pod on scale-out TP servers successfully.
Fixes # N/A
This PR depends on PR #1362.
Test is done in local scale-out 1 x 1 running on Ubuntu20.04.
> [Arktos-Mizar-Integration][ScaleOut]For starting mizar-operator pod on scale-out TP servers successfully

- cluster/gce/util.sh
> /kind bug
replace kubectl with ${KUBE_ROOT}/cluster/kubectl.sh when start-mizar-scaleout
Fixes #1369 
Tested on clean ubuntu 20.04: started scale-out 1x1 with mizar
```
$ kubectl --version
kubectl: command not found
```
```
$ ./cluster/kubectl.sh get pods -AT -owide --kubeconfig=/home/sonyali/go/src/arktos/cluster/kubeconfig.tp-1 | grep mizar
system   default       mizar-daemon-7d9b8bfd48-x8zj6                               6140887095703380146   1/1     Running             0          32m   10.40.0.2   sonyaubuntu1-021822-tp-1-master              <none>           <none>
system   default       mizar-daemon-fccrb …
```
> fix kubectl missing error for scale-out

- cluster/gce/gci/configure.sh
/kind bug
This PR is part of fixes to #1357. The more important fix is from mizar:dev side. This PR only solves the kube-up scale-out preliminary step related issue.
As the preliminary step, it does not download mizar cni binary and have it installed. Instead, it only ensures the cni binary folder is there. The full-fledged mizar installation will be done by daemonset or other means.
With this change, kubelet will not invoke the possibly polluted cni binary before the proper mizar parts are there.
Fixes #1357 
```release-note
None
```
> mizar preliminary installation not to install binary

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/configure.sh
- cluster/gce/manifests/kube-proxy.manifest
- cluster/gce/util.sh
- third_party/mizar/mizar-crds.yaml
- third_party/mizar/mizar-daemon-tpmaster.yaml
- third_party/mizar/mizar-daemon.yaml
- third_party/mizar/mizar-operator.yaml
1.  kube-proxy of rp nodes connecting to tp masters2. 
2. multitenancy network isolation for n-TP x n-RP scale out architecture3. 
3. Deploy mizar daemon and operator after tp and rp ready4. 
4. mizar preliminary installtion does not have binary installed
Fixes #
Tested on scenarios blow:
1.Kubeup (scale up) with mizar: successfully except known pods issue (event-exporter, kubernetes-dashboard pods failure)
```
$ kubectl get pods -AT | grep mizar
system   default       mizar-daemon-blvc5                                   7161814908282533227   1/1     Running            0          15m
system   default       mizar-daemon-rgjk6 …
```
> Kubeup scaleout mizar support

- pkg/kubelet/config/common.go
/kind bug
This PR changes kubelet code to assign really unique UID value to static pods.
The current code has a subtle bug: it generated uid based on pod spec content only, as it call hasher.reset method (in DeepHashObject) right after it takes nodename/source into hasher.
This code change actually fixes the TP-1 scheduler crashing issue in scale-out cluster.
Fixes #1386 
```release-note
NONE
```
> static pods on different nodes get unique uids

- pkg/kubelet/config/common.go
/kind bug
this is back port from master PR#1393, for evaluation in POC branch only.
Fixes #
please don't provide review for this PR. If you have comments, you are welcome to feeding back on PR#1393
```release-note
```
> (backport to POC) static pods on different nodes are assigned unique uid

- pkg/controller/mizar/mizar-arktos-network-controller.go
- pkg/controller/mizar/mizar-arktos-network-controller_test.go
Check in this change for Hong's further test for ContainerCreating issue
> VPC start ip range fix: only generate ip start from range [11, 19]U[21,99]

- cluster/common.sh
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
kube-up.sh support  VPC range for each TP
Fixes #
No additional env added when start  cluster, kube-up will automatically assign vac range for each TP between 11-99.
Tested on scenarios blow:
1. Kubeup (scale up) with mizar: successfully and vpc_range bound to kube-controller-manger
2. Kubeup (scale up with default network): successfully, no vpc_range bound to kube-controller-manger
3. Kubeup (scale up with default network) + kubemark ( scale up with default network: 100 nodes): successfully
4. Kubeup (scale out 1x1, 2x2) with mizar: successfully and TP servers have vpc_range bound to kube-controller-manger
**Does this PR introduce a …
> kube-up support vpc range
