CentaurusInfra/arktos

- staging/src/k8s.io/apimachinery/pkg/watch/watch.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
- test/integration/apiserver/apiserver_partition_test.go
- test/integration/framework/master_utils.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Refactor apiserver parition integration tests + go fmt

- test/integration/apiserver/apiserver_partition_test.go
. Watch from one api server can only get part of data
. Aggregated watch built from multiple api server config can get all data
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Integration tests for api server partition

- hack/arktos_copyright.sh
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: sed updates the file timestamps whether it actually updates the file or not. this may trigger generated files to be updated. fix sed to preserve the original timestamp always.
**Which issue(s) this PR fixes**: #3 
Fixes #
```release-note
```
> Preserve the original timestamp when copyright sed operates on files.

- staging/src/k8s.io/client-go/tools/record/events_cache.go
Set the event tenant in the event aggregator.
> set tenant properly in event aggregator

- hack/testdata/auth-tokens.csv
this file was changed in old PR but I forgot to remove the change before merging.
> reverted a file

- hack/arktos-apiserver-partition.sh
- hack/arktos-up.sh
- hack/create-kubeconfig.sh
- hack/lib/common.sh
- hack/lib/etcd.sh
> Added start apiserver and workload controller manager script

- hack/arktos-up.sh
- hack/lib/etcd.sh
Fixed 2 environment issues
1. Commented /usr/bin/env bash 
2.  Add check condition statement for eth0
> Fixed the 2 environment issues bash head and eth0 interface

- CHANGELOG/CHANGELOG-0.1.md
- CHANGELOG/CHANGELOG-0.2.md
- CHANGELOG/README.md
Add change logs for v0.2 release (330 milestone), and also add the missing change log for v0.1 (130 milestone).
The items and descriptions are from the release note.
> add change logs for 0.1(130 release) and 0.2(330 release)

- pkg/controller/job/job_controller.go
- pkg/controller/job/job_controller_test.go
Part of Issue https://github.com/futurewei-cloud/arktos/issues/186
Enable multi-tenancy in job controller. 
Job is created using the tenant info provided by request.
Tested with both added unit tests and local E2E.
> Enable multi-tenancy in job controller

- pkg/registry/rbac/clusterrolebinding/policybased/BUILD
- pkg/registry/rbac/clusterrolebinding/policybased/storage.go
- pkg/registry/rbac/escalation_check.go
- pkg/registry/rbac/rolebinding/policybased/storage.go
Add support for cluster-role binding in multi-tenancy.
> fix clusterrole binding

- staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
> remove debugging line

- build/root/Makefile
>
> /kind bug
> /kind design
> /kind flake
output logs of failed integration tests for investigation
Fixes #
```release-note
```
> Output logs of failed integration tests

- test/kubemark/start-kubemark.sh
Changes to be committed:
modified:   test/kubemark/start-kubemark.sh
/kind bug
Fixes #
https://github.com/futurewei-cloud/arktos/issues/240
regression of e30717c#diff-52ac7976c49df8a19c7a527bc1f08150
```release-note
```
> fix issue: https://github.com/futurewei-cloud/arktos/issues/240

- docs/design-proposals/multi-tenancy/multi-tenancy-api-resource-model.md
> multi-tenancy CRD design

- hack/setup-dev-node.sh
/kind enhancement
Add a script to install prerequisites of an Arktos development environment for convinience.
Fixes #
It's been tested on a fresh installation of Ubuntu 18.04 and 16.04.
After running this script, arkto-up.sh can successfully boot up a single-node cluster.
no
```release-note
```
> Add a script to setup a dev node

- staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go
- staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
- Missing checks for edge cases
- A bug that could cause index out of bound with invalid input
- No unit testing
Added stricter checks for edge cases, fixed the bug and add full-fledged unit tests
Also tested e2e in local environment with tenant creation, role assignment, and rbac accesses.
- Make update was also run but didn't generate additional changes.
- TDD is fun :) 
Thanks @chenqianfzh for reporting this issue.
> improve tenant extraction from x509 cert

- cluster/kube-down.sh
This is hotfix that $PRESET_INSTANCES_ENABLED could be used without value
/kind bug
> Need check $PRESET_INSTANCES_ENABLED with default value

- cluster/gce/gci/BUILD
- cluster/gce/gci/apiserver_manifest_test.go
- pkg/controller/service/BUILD
- pkg/kubelet/container/runtime.go
fix copyright issue
Fixes #
```release-note
```
> fix copyright for apiserver_manifest_test.go

- hack/arktos_copyright.sh
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Currently, copyright tool does not catch files that have not been checked in, but are staged with intent to commit. This PR applies copyright processing to staged files as well.
Fixes #
```release-note
```
> Apply copyright processing on files that are staged for commit as well.

- pkg/controller/cronjob/cronjob_controller.go
- pkg/controller/cronjob/cronjob_controller_test.go
- pkg/controller/cronjob/injection.go
- pkg/controller/cronjob/utils_test.go
- test/integration/cronjob/cronjob_test.go
```bash
TENANT            NAMESPACE             NAME                            HASHKEY               READY   STATUS      RESTARTS   AGE
system            default               pod/hello-1591122540-wxqxx      4499293502300637533   0/1     Completed   0          2m25s
system            default               pod/hello-1591122600-dl66g      8019492892732101096   0/1     Completed   0          85s
system            default               pod/hello-1591122660-fv2x7      4182720084568201888   0/1     Completed   0          25s
futureweitenant   futurewei-namespace   pod/hello-1591122540-r44jf      5058905202205607190   0/1     Completed   0          2m25s
futureweitenant   futurewei-namespace   pod/hello-1591122600-79lt8      7850712421755160416   0/1     Completed   0          85s …
```
> make cron job controller multi-tenant

- hack/lib/common.sh
- pkg/kubelet/util/podConverter/podConverter.go
> /kind bug
Arktos runtime issue 27:set resources from vm to container,
Arktos issue 308: ignore ssl check with wget when getting runtime deployment files
**Which issue(s) this PR
#308
> VM memory resource is not set per resource requested

- docs/setup-guide/multi-tenancy-setup.md
- hack/setup-multi-tenancy/create_tenant.sh
- hack/setup-multi-tenancy/setup_client.sh
Tracking issue: https://github.com/futurewei-cloud/arktos/issues/337
No additional tests performed as the scripts added are tested as detailed by the added doc.
> added scripts and guide for user to setup tenant and access

- hack/make-rules/update.sh
"make update" should return 1 if there is file updated. This is to hook up pr ci check to avoid miss running of "make update".
/kind EE
> "make update" should return 1 if there is file updated. 

- docs/setup-guide/arktos-apiserver-partition.md
- hack/arktos-apiserver-partition.sh
- hack/lib/common.sh
. Support skip build
. Remove no longer used start_workload_controller_manager/start_kube_controller_manager/start_kube_scheduler/start_kubelet/start_kube_proxy
. Refactor arktos-apiserver-partition.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> apiserver partition start up script refactor:

- pkg/controller/tenant/tenant_controller.go
- pkg/controller/tenant/tenant_controller_test.go
- test/integration/BUILD
- test/integration/tenantcontroller/BUILD
- test/integration/tenantcontroller/main_test.go
- test/integration/tenantcontroller/tenantcontroller_test.go
Part of https://github.com/futurewei-cloud/arktos/issues/205
This test verifies an "admin" cluster role and rolebinding are provisioned when a new tenant is created.
> add integration test for tenant cluster role and binding provisioning

- cluster/images/etcd/Makefile
- hack/lib/etcd.sh
> Added Customized ETCD v3.4.4.1 into arktos repo

- cluster/images/etcd/Makefile
- hack/lib/etcd.sh
> Updated etcd version from 3.4.4.1 to 3.4.4-arktos.1

- staging/src/k8s.io/client-go/apiserverupdate/update.go
https://github.com/futurewei-cloud/arktos/issues/408
> Fix unlock of unlocked mutex bug in api server endpoints update

- hack/install-etcd.sh
- hack/lib/etcd.sh
- hack/make-rules/update.sh
- hack/update-etcd.sh
Added etcd to make update
Improved etcd version comparision
> Added etcd to make update

- staging/src/k8s.io/apimachinery/pkg/watch/watch.go
Fix issue https://github.com/futurewei-cloud/arktos/issues/387
> Fix "send on closed channel" bug in aggregated watch

- README.md
added reference to hack/setup-dev-env.sh in the main README.
> add setup script info to readme

- hack/lib/etcd.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Add cluster-id to ETCD start argument

- test/integration/apimachinery/BUILD
- test/integration/master/BUILD
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> increase apimachinery integration test tiemout

- pkg/apis/core/types.go
- pkg/kubelet/BUILD
- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/kuberuntime/kuberuntime_manager.go
- pkg/kubelet/util/podConverter/podConverter.go
- plugin/pkg/admission/podresourceallocation/admission.go
- plugin/pkg/admission/podresourceallocation/admission_test.go
- staging/src/k8s.io/api/core/v1/types.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
**What this PR does / why we need it**: Arktos design supports In-Place restart-free vertical resizing of Pods for both container and VM workloads in a unified way. The full container vertical scaling feature was checked in earlier. This PR adds support for VM vertical scaling on the kubernetes-side (separate PR from Yunwen in runtime repo will bring the runtime-side of the work).
**Which issue(s) this PR fixes**: #223 
Fixes #
Verified by performing memory and cpu …
> Vertical Scaling for VMs (in addition to containers)

- pkg/apis/core/validation/validation.go
- pkg/controller/tenant/tenant_controller.go
- pkg/registry/core/storagecluster/storage/storage_test.go
- staging/src/k8s.io/apimachinery/pkg/util/diff/compare.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/errors.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/test_server.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
- staging/src/k8s.io/apiserver/pkg/storage/interfaces.go
- staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
- staging/src/k8s.io/apiserver/pkg/storage/storagecluster/storageclustermanager.go
- staging/src/k8s.io/apiserver/pkg/storage/storagecluster/tenantstoragemapmanager.go
- staging/src/k8s.io/apiserver/pkg/storage/storagecluster/update.go
- test/integration/etcd/data.go
- test/integration/etcd/multi_tenancy_data.go
- test/integration/etcd/server.go
- test/integration/framework/util.go
- test/integration/kubelet/watch_manager_test.go
- test/integration/tenantcontroller/tenantcontroller_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> ETCD partition part 3: support paginated list

- docs/design-proposals/etcd/ETCD-Data-Partition-Design.md
- docs/setup-guide/arktos-apiserver-partition.md
> Add ETCD data partition into manual

- test/e2e/arktos/multi-tenancy/README.md
- test/e2e/arktos/multi-tenancy/helper/config-e2e-test.sh
- test/e2e/arktos/multi-tenancy/helper/e2e-test-helper.sh
- test/e2e/arktos/multi-tenancy/run-e2e-test.sh
- test/e2e/arktos/multi-tenancy/testcase/basic_tests
- test/e2e/arktos/multi-tenancy/testcase/new_tenant_tests
This PR presents the e2e Arktos kubectl test script and some sample test case files. Only a few test cases are created for example. Once this PR is approved and consensus is reached on how to implement the e2e tests in Arktos, more test cases will be added.
A readme.md is also part of the PR,  which gives detailed description on how to run the tests and create test cases.
The following is a video of a test run using the test script and test case files in this PR:
Following are some the screenshots the test runs in different cases:
1. The test terminates when the cluster is not up.
2. The test cases all passed.
3. Some test cases failed .
> kubectl e2e test script

- cmd/workload-controller-manager/BUILD
- cmd/workload-controller-manager/main.go
Also remove none used multiple kubeconfig files supports
> Workload controller manager: use protobuf as request content instead of default json

- cluster/common.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/manifests/etcd-empty-dir-cleanup.yaml
- cluster/gce/manifests/etcd.manifest
- cluster/gce/upgrade-aliases.sh
- cluster/gce/util.sh
- cluster/images/etcd-empty-dir-cleanup/Makefile
- cluster/images/etcd/Dockerfile
- cluster/images/etcd/Makefile
- cluster/images/etcd/README.md
- cluster/images/etcd/migrate-if-needed.sh
- cmd/kubeadm/app/constants/constants.go
- cmd/kubeadm/app/constants/constants_test.go
- vendor/go.etcd.io/etcd/version/version.go
> Fixed the issue that kube-up does not pick up etcd3.4.4-arktos.1

- docs/setup-guide/arktos-apiserver-partition.md
Added storage cluster id to a yaml files for testing.
> Updated a tenant test yaml file

- test/kubemark/gce/util.sh
> /kind bug
allow setting master_root_disk_size when start kubemark
Fixes #
```release-note
```
> allow setting master_root_disk_size when start kubemark

- staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
> /kind bug
In 10K-node scalability test, API Server crashed due to a nil pointer dereference.  It was because a nil item was returned from watch cache.  This PR fixes the issue.
In the watch cache, revCache acts as a pointer to the actual items in Cache. When we delete one item, we should first delete (or overwrite) the pointer. If we delete the object before overwriting the pointer, another thread could read a pointer but couldn’t find the associated item in the map Cache, and therefore get a nil item.
Fixes #555
No
No
> Fix a nil pointer crash caused by a race condition in watch cache

- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/status/status_manager.go
- pkg/kubelet/util/format/pod.go
- pkg/volume/util/operationexecutor/operation_executor.go
Update log for stress related issues
Need more info from log to investigate stress test issues
> Update logging for more info to investigate stress related issues

- pkg/kubelet/kuberuntime/helpers.go
- pkg/kubelet/kuberuntime/kuberuntime_manager.go
- pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
> /kind bug
stress testing was blocked
Fixes #
None
> Enforce Rlock for pod-runtime map and use of map operation functions

- pkg/scheduler/eventhandlers.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Add pod create event to scheduler

- pkg/master/BUILD
- pkg/master/controller_test.go
- pkg/master/reconcilers/BUILD
- pkg/master/reconcilers/lease_test.go
- pkg/printers/internalversion/printers_test.go
- pkg/registry/core/controllerinstance/storage/storage_test.go
- pkg/registry/core/storagecluster/storage/storage.go
Issue https://github.com/futurewei-cloud/arktos/issues/568
> Increase UT test coverage for api server/etcd data partition - part 1

- pkg/kubelet/kubelet.go
/kind bug
This PR fixes the bug that kubelet mistakenly skips syncLoopIteration when cni is not installed yet.
Some cni plugins, like Flannel etc, are installed after the cluster has been started (without cni installed initially, however). If kubelet is unable to start cni pods, it will dead lock, and the cluster cannot run any pods at all. 
This PR removes the premature error returning code introduced in implementation of runtime partial readiness feature, hence breaks the dead lock.
Fixes #595
NONE
> kubelet should not skip pod synchronization when network is not ready

- staging/src/k8s.io/apiserver/pkg/storage/datapartition/BUILD
- staging/src/k8s.io/apiserver/pkg/storage/datapartition/datapartitionmanager_test.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
- staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
- staging/src/k8s.io/apiserver/pkg/storage/storagecluster/BUILD
- staging/src/k8s.io/apiserver/pkg/storage/storagecluster/storageclustermanager_test.go
- staging/src/k8s.io/apiserver/pkg/storage/storagecluster/tenantstoragemapmanager_test.go
Issue https://github.com/futurewei-cloud/arktos/issues/568
> UT coverage increase for vendor/apiserver/storage

- hack/arktos-worker-up.sh
/kind feature
provide cluster admin with script tool to add more worker nodes to Arktos lab cluster.
Arktos lab env started by hack/arktos-up.sh is single node only. This PR provides a script for user to add more worker nodes to the existing Arktos cluster.
Due to the development status that kube-proxy is not ready for multi-tenant Arktos cluster, the worker nodes will run kubelet agent only, not including kube-proxy. 
Fixes #612
YES
```release-note
Cluster admin can add more worker nodes. For instance, running below commands in GCP env will add a new worker node:
$ export KUBELET_IP=10.138.0.18   //assuming the work node has IP …
```
> add arktos worker node

- docs/setup-guide/multi-node-dev-cluster.md
updated the instructions of adding worker nodes to arktos cluster.
Fixes #618
None for arktos cluster
> doc: instruction of adding new worker nodes with quirk of k8s service iptables rule

- CHANGELOG/CHANGELOG-0.5.md
- CHANGELOG/README.md
Add CHANGELOG for the 830 release (release 0.5)
Fixes #560
No
No
> Add CHANGELOG for release 0.5

- pkg/cloudfabric-controller/controllerframework/controller_framework.go
Fix issue https://github.com/futurewei-cloud/arktos/issues/659
> Bug fix for no change in WCM.

- build/root/Makefile
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> export log when tests fail

- cmd/edgegateway/app/options/options.go
- cmd/edgegateway/app/options/validation.go
- cmd/edgegateway/app/server.go
- cmd/edgegateway/edgegateway.go
- pkg/apis/edgegateway/register.go
- pkg/apis/edgegateway/v1/types.go
- pkg/edgegateway/common/constants/default.go
- pkg/edgegateway/common/modules/group.go
- pkg/edgegateway/common/modules/names.go
- pkg/edgegateway/edgehub/config/config.go
- pkg/edgegateway/edgehub/edgehub.go
> /kind design
add edgegateway
> add edgegateway

- cmd/edgegateway/app/options/options.go
- cmd/edgegateway/app/server.go
- pkg/apis/edgegateway/v1/types.go
- pkg/edgegateway/edgehub/clients/adapter.go
- pkg/edgegateway/edgehub/clients/factory.go
- pkg/edgegateway/edgehub/clients/quicclient/quicclient.go
- pkg/edgegateway/edgehub/clients/wsclient/websocket.go
- pkg/edgegateway/edgehub/config/config.go
- pkg/edgegateway/edgehub/edgehub.go
- pkg/edgegateway/edgehub/process.go
1. init a client to connect to cloud
2. send heartbeat to cloud
> edgegateway connect to cloudgateway

- staging/src/k8s.io/client-go/apiserverupdate/update.go
- staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
- staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager_test.go
Issue https://github.com/futurewei-cloud/arktos/issues/687
> API server config read lock.

- pkg/cloudgateway/cloudhub/channelq/channelq.go
- pkg/cloudgateway/cloudhub/common/model/types.go
- pkg/cloudgateway/cloudhub/handler/messagehandler.go
- pkg/edgegateway/edgehub/process.go
> /kind bug
> /kind design
> /kind flake
1. send message to edgegateway from cloudgateway.
2. receive message from edgegateway and send it to controllers of cloud.
> add cloudgateway message processing

- pkg/cloudgateway/cloudhub/channelq/channelq.go
- pkg/cloudgateway/cloudhub/handler/messagehandler.go
- pkg/cloudgateway/common/constants/default.go
- pkg/edgegateway/common/constants/default.go
- pkg/edgegateway/edgehub/edgehub.go
- pkg/edgegateway/edgehub/process.go
>
> /kind bug
> /kind design
> /kind flake
1. receive message from cloudgateway and send it to modules of edge.
2. send message to cloudgateway.
3. cloudgateway handle response message from edgegateway.
> add edgegateway message processing

- cmd/cloudgateway/app/options/options.go
- cmd/edgegateway/app/options/options.go
- pkg/apis/cloudgateway/v1/types.go
- pkg/apis/edgegateway/v1/types.go
- pkg/cloudgateway/cloudhub/channelq/channelq.go
- pkg/cloudgateway/cloudhub/common/model/types.go
- pkg/cloudgateway/cloudhub/handler/messagehandler.go
- pkg/cloudgateway/cloudhub/servers/httpserver/server.go
- pkg/edgegateway/common/constants/default.go
- pkg/edgegateway/edgehub/certificate/certmanager.go
- pkg/edgegateway/edgehub/clients/factory.go
- pkg/edgegateway/edgehub/clients/quicclient/quicclient.go
- pkg/edgegateway/edgehub/clients/wsclient/websocket.go
- pkg/edgegateway/edgehub/common/http/http.go
- pkg/edgegateway/edgehub/config/config.go
>
> /kind bug
> /kind design
> /kind flake
fix name, nodename->siteID
> fix name problem

- staging/src/k8s.io/apimachinery/pkg/watch/watch.go
- staging/src/k8s.io/apimachinery/pkg/watch/watch_test.go
- staging/src/k8s.io/client-go/tools/cache/reflector.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Aggregated watcher recover

- pkg/cloudgateway/cloudhub/channelq/channelq.go
- pkg/cloudgateway/cloudhub/handler/messagehandler.go
- pkg/cloudgateway/cloudservice/cloudservice.go
- pkg/cloudgateway/cloudservice/httpservice/httpclient.go
- pkg/cloudgateway/cloudservice/router.go
- pkg/cloudgateway/common/modules/name.go
- pkg/edgegateway/common/modules/group.go
- pkg/edgegateway/edgehub/process.go
- pkg/edgegateway/edgeservice/edgeservice.go
- pkg/edgegateway/edgeservice/httpservice/httpserver.go
cloud-edge service communication with http
> cloud-edge service communication with http

- cmd/kube-controller-manager/app/mizarcontrollers.go
- pkg/controller/mizar/mizar-arktos-network-controller.go
- pkg/controller/mizar/mizar-service-controller.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Add retry when "temp error" is returned from mizar
Also adding work around for current dns issue and crd event listing issue
Fixes #
```release-note
```
> Modify service controller

- pkg/controller/mizar/mizar-service-controller.go
> Fix tiny issue found during testing: info should be infof

- cmd/cloudgateway/app/server.go
- pkg/cloudgateway/cloudhub/cloudhub.go
- pkg/cloudgateway/cloudhub/config/config.go
- pkg/cloudgateway/cloudhub/servers/httpserver/secretsutil.go
- pkg/cloudgateway/cloudhub/servers/httpserver/server.go
- pkg/cloudgateway/cloudhub/utils/gatewayclient.go
- pkg/cloudgateway/cloudhub/utils/kubeclient.go
- pkg/cloudgateway/cloudservice/httpservice/httpserver.go
- pkg/cloudgateway/cloudservice/router.go
- pkg/cloudgateway/cloudservice/utils/utils.go
> /kind design
provide gateway client, and get service and site by gateway client.
> get service and site by gateway client

- docs/design-proposals/multi-tenancy/multi-tenancy-api-resource-model.md
Update the doc about forced-sharing system CRD.
> update multi-tenancy design doc about forced-sharing CRD

- cluster/gce/manifests/etcd.manifest
It does not matter. However, it is better to fix it.
> Added a missing quote in etcd.manifest

- OWNERS
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
update to a real owners file
Fixes #
```release-note
```
> update OWNERS file to work with bot

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Use the correct owner id.
Fixes #
```release-note
```
> Replace panda with yxiong2020

- cmd/kube-controller-manager/app/mizarcontrollers.go
- pkg/controller/mizar/BUILD
- pkg/controller/mizar/grpc_adaptor.go
- pkg/controller/mizar/grpc_adaptor_mock.go
- pkg/controller/mizar/mizar-arktos-network-controller.go
- pkg/controller/mizar/mizar-endpoints-controller.go
- pkg/controller/mizar/mizar-node-controller.go
- pkg/controller/mizar/mizar-pod-controller.go
- pkg/controller/mizar/mizar-service-controller.go
- pkg/controller/mizar/mizar_node_controller_test.go
- pkg/controller/mizar/testutil.go
- pkg/controller/mizar/util.go
- pkg/controller/mizar/util_test.go
This is to add unit test for mizar node controller
/kind test
> Add test cases for mizar node controller

- staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
- staging/src/k8s.io/apiserver/pkg/storage/storagecluster/tenantstoragemapmanager.go
Use local mux (instead of object level) for list append in ETCD store.
Rename store.mux to be dataClientMux
Add some trace for performance test (original author: Xiaoning)
> Mux bug fix in ETCD store for partition

- cmd/cloudgateway/app/options/options.go
- cmd/cloudgateway/app/server.go
- cmd/edgegateway/app/options/options.go
- cmd/edgegateway/app/server.go
- pkg/apis/cloudgateway/v1/types.go
- pkg/apis/edgegateway/v1/types.go
- pkg/cloudgateway/cloudhub/channelq/channelq.go
- pkg/cloudgateway/cloudmesh/cloudmesh.go
- pkg/cloudgateway/common/modules/group.go
- pkg/cloudgateway/common/modules/name.go
- pkg/edgegateway/common/modules/group.go
- pkg/edgegateway/common/modules/names.go
- pkg/edgegateway/edgemesh/edgemesh.go
> /kind design
1. add new module cloudmesh and api
2. add new module edgemesh and api
> add new modules: cloudmesh and edgemesh

- cmd/cloudgateway/app/options/options.go
- cmd/edgegateway/app/options/options.go
- pkg/apis/cloudgateway/v1/types.go
- pkg/apis/edgegateway/v1/types.go
- pkg/cloudgateway/cloudmesh/cloudmesh.go
- pkg/cloudgateway/cloudmesh/config/config.go
- pkg/cloudgateway/cloudmesh/server/server.go
- pkg/cloudgateway/cloudmesh/taptun/taptun.go
- pkg/edgegateway/edgemesh/client/client.go
- pkg/edgegateway/edgemesh/config/config.go
- pkg/edgegateway/edgemesh/edgemesh.go
- pkg/edgegateway/edgemesh/process.go
- pkg/edgegateway/edgemesh/taptun/taptun.go
> /kind design
1. provide a websocket server in cloudmesh
2. provide a websocket client in edgemesh
3. the communication between cloud services and edge services is realized by websocket
> add data plane message communication between cloud and edge site

- pkg/cloudgateway/cloudmesh/cloudmesh.go
- pkg/cloudgateway/cloudmesh/proxy/proxy.go
- pkg/cloudgateway/common/constants/default.go
- pkg/cloudgateway/common/modules/group.go
- pkg/cloudgateway/controller/handler/serviceexpose_handler.go
- pkg/edgegateway/common/modules/group.go
- pkg/edgegateway/edgemesh/edgemesh.go
> /kind design
1. sync service expose information to cloudmesh
2. cloudmesh set iptables rule
3. cloudmesh set route
> sync service expose information to cloudmesh

- pkg/cloudgateway/controller/handler/serviceexpose_handler.go
- pkg/edgegateway/common/constants/default.go
- pkg/edgegateway/edgehub/process.go
- pkg/edgegateway/edgemesh/edgemesh.go
- pkg/edgegateway/edgemesh/proxy/proxy.go
> /kind design
1. controller sync service expose information to edgemesh
2. cloudmesh set iptables rule
3. cloudmesh set route
> sync service expose information to edgemesh

- pkg/cloudgateway/cloudmesh/proxy/proxy.go
- pkg/cloudgateway/controller/handler/serviceexpose_handler.go
- pkg/edgegateway/edgemesh/proxy/proxy.go
> /kind design
after deleting the exposed service, delete iptables rules and routes.
> delete related information after deleting exposed service

- pkg/apis/cloudgateway/v1/types.go
- pkg/cloudgateway/cloudmesh/proxy/proxy.go
- pkg/cloudgateway/common/constants/default.go
- pkg/cloudgateway/controller/handler/serviceexpose_handler.go
- pkg/edgegateway/common/constants/default.go
- pkg/edgegateway/edgemesh/proxy/proxy.go
> /kind design
1. add tap ip address in site API
2. add route by site tap ip address
> get tap ip address in site information

- cmd/cloudgateway/app/options/options.go
- pkg/apis/cloudgateway/v1/types.go
- pkg/cloudgateway/cloudmesh/config/config.go
- pkg/cloudgateway/cloudmesh/proxy/proxy.go
- pkg/cloudgateway/cloudmesh/server/server.go
- pkg/cloudgateway/controller/handler/serviceexpose_handler.go
- pkg/edgegateway/edgemesh/client/client.go
- pkg/edgegateway/edgemesh/config/config.go
- pkg/edgegateway/edgemesh/proxy/proxy.go
> /kind bug
> /kind design
On the cloud, instead of using only one interface, there will be one interface for each site that connects to it. In this way, it can avoid every site receiving all messages from the cloud, , even though the message is not intended for this site.
> update the usage of tap interface on the cloud

- pkg/cloudgateway/cloudmesh/proxy/proxy.go
- pkg/edgegateway/edgemesh/proxy/proxy.go
> /kind bug
Update the iptables settings to avoid setting the same iptables.
> fix iptables settings

- pkg/cloudgateway/controller/handler/serviceexpose_handler.go
> /kind design
If none of the virtual presence IP addresses of the site is used, delete the virtual presence information of the site from map.
> update ReleaseVirtualPresence function

- cluster/common.sh
- cluster/images/etcd-empty-dir-cleanup/Makefile
- cluster/images/etcd/Makefile
- hack/lib/etcd.sh
>
etcd image repo moved from futurewei-cloud to centaurus-cloud
Fixes #
```release-note
```
> update etcdimage from futurewei-cloud to centaurus-cloud

- cmd/kube-proxy/app/BUILD
- cmd/kube-proxy/app/server.go
- cmd/kubelet/app/server.go
- staging/src/k8s.io/client-go/datapartition/BUILD
- staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Change fieldSelector value in APIServerConfigManager

- CONTRIBUTING.md
- README.md
- SUPPORT.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Update readme, support, contribute doc with new project links.

- docs/setup-guide/scale-out-poc-setup.md
- hack/arktos-up-scale-out-poc.sh
- hack/scale_out_poc/nginx.conf
- hack/scale_out_poc/setup_nginx_proxy.sh
This PR 
1. automate the nginx proxy setup 
2. remove some unnecessary setup in resource partition
Verification:
Tried in my test AWS machines with two different configs:
1. the proxy installed in the tenant partition
2. the proxy installed in the resource partition
> automate proxy config in scale-out setup

- pkg/kubelet/nodelease/BUILD
- pkg/kubelet/nodelease/controller.go
> Make sure lease create/renew can use different api server

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Tune nginx params, drop service account.
Fixes #
```release-note
```
> Drop service account param, tune up nginx params

- cluster/gce/util.sh
- cmd/kubelet/app/options/options.go
- cmd/kubelet/app/server.go
- cmd/kubemark/hollow-node.go
- hack/arktos-up-scale-out-poc.sh
- hack/scale_out_poc/two_TP/nginx.conf
- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_getters.go
- pkg/kubelet/kubelet_node_status.go
- pkg/kubelet/kubelet_pods.go
- pkg/kubelet/kubelet_test.go
- pkg/kubelet/pod_actions.go
- pkg/kubelet/runonce_test.go
- pkg/kubelet/secret/secret_manager.go
- pkg/kubelet/status/status_manager.go
- pkg/kubelet/volume_host.go
- pkg/kubemark/hollow_kubelet.go
- test/kubemark/gce/util.sh
- test/kubemark/resources/hollow-node_template.yaml
- test/kubemark/start-kubemark.sh
From scale-out-poc branch back to m1 branch. kubelet, kubemarkt node side changes.
> Cherry pick kubelet related changes to scale-out-poc-m1 branch + minor bug fix

- perf-tests/clusterloader2/testing/arktos/tenant1.yaml
- perf-tests/clusterloader2/testing/arktos/tenant2.yaml
- test/kubemark/start-kubemark.sh
In testing. currently we can manually perform this in our test env.
> Create POC test tenants with kubemark test

- staging/src/k8s.io/component-base/cli/globalflag/globalflags_test.go
- vendor/k8s.io/klog/.travis.yml
- vendor/k8s.io/klog/README.md
- vendor/k8s.io/klog/go.mod
- vendor/k8s.io/klog/go.sum
- vendor/k8s.io/klog/klog.go
- vendor/modules.txt
https://github.com/kubernetes/kubernetes/commit/c2a4906152e67a45308f988aa2cb8b76b4503855
committed on Sep 23, 2019
Update to latest klog 0.4.0
https://github.com/kubernetes/kubernetes/commit/9a2de95601641aa1077734c76fc24ebe7b6026db
committed on Aug 8, 2019
Skipped dependent go.mod/go.sum updates. Will do it separately
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Bump k8s.io/klog to v1.0.0

- test/kubemark/start-kubemark.sh
This PR create two kubeconfig files, directly connected to TP1/TP2, instead of the the proxy, under the folder test/kubemark/resources, when running start-kubemark.sh.
> create direct TP kubeconfig in kubemark test

- pkg/kubelet/kubelet_pods.go
- test/kubemark/start-kubemark.sh
A temp hacky way to address one of the situations that leads pods in terminating stage.
> workaround a pod terminating issue in perf

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/partitionserver-configure-helper.sh
- cluster/gce/util.sh
- cluster/validate-cluster.sh
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: This is needed for running large scale perf tests
Fixes #
```release-note
```
> Increase openfile and socket limits for nginx process

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/partitionserver-configure-helper.sh
- cluster/gce/util.sh
- cluster/validate-cluster.sh
- pkg/kubelet/kubelet_pods.go
- test/kubemark/resources/hollow-node_template.yaml
- test/kubemark/start-kubemark.sh
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: This is intended to help reduce load on proxy.
Fixes #
```release-note
```
> Disable kube-proxy, connect NPD directly to RP master

- cluster/gce/gci/configure-helper-common.sh
disable it as it cause perf-regressions.
> Disable network object creation in kubemark

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/util.sh
add changes from the following commits to enable prometheus in scale-out cluster
https://github.com/futurewei-cloud/arktos-perftest/commit/e5f6915b1603e29fc76f6ec6af3739573165ddd8
https://github.com/futurewei-cloud/arktos-perftest/commit/c808cf317b2a0d6b16a672f1cfe81709c3c54a2b
> enable prometheus for scale-out 

- test/kubemark/resources/hollow-node_template.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
**What this PR does / why we need it**: This may help with the 5k test by reducing load on haproxy
Fixes #
```release-note
```
> Remove kube-proxy from hollow node pod

- cmd/kube-controller-manager/app/core.go
- pkg/controller/replicaset/replica_set.go
- staging/src/k8s.io/client-go/util/flowcontrol/throttle.go
Fixing the issue that replica-set controller was set to 8000. It should be caused by shared config which was multiplied by 20 by the tenant controller and namespace controller.
> fix controller QPS issue

- cluster/gce/util.sh
- hack/BUILD
- hack/scale_out_poc/config_haproxy/cfg_generator/BUILD
- hack/scale_out_poc/config_haproxy/cfg_generator/cfg_generator.go
- hack/scale_out_poc/config_haproxy/cfg_generator/util.go
- hack/scale_out_poc/config_haproxy/haproxy.cfg.template
- hack/scale_out_poc/config_haproxy/setup_haproxy.sh
- test/kubemark/gce/util.sh
- test/kubemark/start-kubemark.sh
- test/kubemark/stop-kubemark.sh
This PR includes two commits:
1. Commit 1: a tool to generate haproxy.cfg for multiple TPs
2. Commit 2: Test script change to generate test clusters of multiple TPs,where the number of TPs is specified in env var SCALEOUT_TP_COUNT
Verification: 
Created clusters of 2-TP and 3-TP respectively, and verified:
1. TPs are created correctly
2. Haproxy.cfg is correct
3. 100-node perf-test passed
> Multi TP Test Cluster Creation

- build/build-image/cross/Dockerfile
- hack/lib/golang.sh
- pkg/kubelet/cm/cgroup_manager_unsupported.go
- pkg/kubelet/cm/helpers_unsupported.go
- pkg/kubelet/kuberuntime/helpers_unsupported.go
- pkg/kubelet/kuberuntime/kuberuntime_container_unsupported.go
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: This disable building arktos for windows platform. It is not supported in arktos, and our implementation of vertical scaling does not support it as well. This enables make release to successfully work.
Fixes #
```release-note
```
> Disable windows build - not supported in arktos

- hack/scale_out_poc/config_haproxy/setup_haproxy.sh
Fix onebox cfg script.
Verifcation done in my dev box.
> fix onebox haproxy cfg script

- test/kubemark/start-kubemark.sh
As we are preparing to run scability test on clusters with 30k or more hollow nodes, the existing config of 30-min timeout to get all nodes ready will be insufficient.
This PR sets the timeout value linear to the number of hollow nodes.
> set wait period per hollow-node #

- perf-tests/clusterloader2/pkg/chaos/nodes.go
- perf-tests/clusterloader2/pkg/execservice/BUILD
- perf-tests/clusterloader2/pkg/execservice/exec_service.go
- perf-tests/clusterloader2/pkg/framework/client/objects.go
- perf-tests/clusterloader2/pkg/framework/framework.go
- perf-tests/clusterloader2/pkg/imagepreload/BUILD
- perf-tests/clusterloader2/pkg/imagepreload/imagepreload.go
- perf-tests/clusterloader2/pkg/measurement/common/bundle/BUILD
- perf-tests/clusterloader2/pkg/measurement/common/bundle/test_metrics.go
- perf-tests/clusterloader2/pkg/measurement/common/metrics_for_e2e.go
- perf-tests/clusterloader2/pkg/measurement/common/probes/probes.go
- perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
- perf-tests/clusterloader2/pkg/measurement/util/informer/BUILD
- perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
- perf-tests/clusterloader2/pkg/measurement/util/object_store.go
- perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/BUILD
- perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
- perf-tests/clusterloader2/pkg/prometheus/experimental.go
- perf-tests/clusterloader2/pkg/prometheus/prometheus.go
- perf-tests/clusterloader2/pkg/test/simple_test_executor.go
- perf-tests/clusterloader2/pkg/util/BUILD
- perf-tests/clusterloader2/pkg/util/multi-tenancy.go
- staging/src/k8s.io/client-go/dynamic/dynamicinformer/informer.go
it is verified working in both scale-out and scale-up kubemark clusters
> migrate multi-tenancy perf-test to master branch

- cmd/BUILD
- cmd/haproxy-cfg-generator/BUILD
- cmd/haproxy-cfg-generator/cfg_generator.go
- cmd/haproxy-cfg-generator/cfg_generator_test.go
- cmd/haproxy-cfg-generator/data/haproxy.cfg.template
- cmd/haproxy-cfg-generator/data/sample_four_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_one_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_three_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_two_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/util.go
- hack/scalability/setup_haproxy.sh
This PR migrates the haproxy config tool  & script from PoC branch to master. Unit tests were also added.
The code change is verified in One-Box. E2E verification will be done after the kubemark changes are migrated.
> migrate haproxy cfg tool/script to master branch

- cmd/kubelet/app/BUILD
- cmd/kubelet/app/server.go
- hack/arktos-up.sh
- pkg/kubelet/kubelet.go
- pkg/registry/cachesize/cachesize.go
Pick up scale up perf test changes back to master:
> Merge perftest back to master

- hack/make-rules/update.sh
file-updated-check happens in pr test. It detects whether people have forgot do "make update" or not by invoking "make update" and check whether there is file updated. The check will show what's the files that got updated. This change is to show more message, that for the updated files, what's the diff between old version and updated version.
/kind test
The pr shows more info that help developer to know what's changed.
> Show more detailed message for file-updated-check

- cmd/kubelet/app/options/options.go
- docs/setup-guide/scale-out-local-dev-setup.md
- hack/arktos-up-scale-out-poc.sh
- hack/lib/common.sh
- hack/lib/util.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Scale-out set up for local dev environment + quick manual

- cmd/kube-scheduler/app/config/config.go
- cmd/kube-scheduler/app/options/deprecated.go
- cmd/kube-scheduler/app/options/options.go
- cmd/kube-scheduler/app/server.go
- docs/setup-guide/scale-out-local-dev-setup.md
- hack/arktos-up-scale-out-poc.sh
- hack/lib/common.sh
- hack/lib/util.sh
- pkg/scheduler/apis/config/types.go
- pkg/scheduler/apis/config/v1alpha1/zz_generated.conversion.go
- pkg/scheduler/apis/config/zz_generated.deepcopy.go
- staging/src/k8s.io/kube-scheduler/config/v1alpha1/types.go
- staging/src/k8s.io/kube-scheduler/config/v1alpha1/zz_generated.deepcopy.go
. Pick up yunwen's scheduler changes.
. Generate RP kubeconfig for scheduler in TP - with SSL enabled
. Works in 2TP/1RP
> Scheduler talks to TPs directly with SSL enabled in dev environment

- hack/lib/common.sh
Tested in 2TP/2RPs, tenant pods created.
> Enable serviceaccount & serviceaccount-token controller in RP local cluster

- hack/lib/common.sh
Fix kube-proxy stop running issue in local scale up cluster
> Fix kube-proxy stop running issue in local scale up cluster

- cluster/addons/rbac/kubelet-cert-rotation/kubelet-certificate-management.yaml
- cluster/addons/rbac/legacy-kubelet-user-disable/kubelet-binding.yaml
- cluster/addons/rbac/legacy-kubelet-user/kubelet-binding.yaml
- cluster/gce/addons/podsecuritypolicies/node-binding.yaml
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
- pkg/kubelet/kubelet.go
- staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
- test/kubemark/resources/start-kubemark-master.sh
> /kind bug
kube-up.sh failed in 430 branch due to missing a critical fix for a regression in master
Fixes #
> Pickup critical bugfix from master to 430 branch

- go.sum
- pkg/controller/podgc/gc_controller.go
- pkg/controller/podgc/gc_controller_test.go
Fix a issue found in https://github.com/CentaurusInfra/arktos/issues/1020
> Fix GC controller delete pod issue for multi-tenancy

- cluster/gce/gci/configure-helper-common.sh
- pkg/kubelet/kubelet.go
> /kind bug
perf test cluster setup in 430 branch
> fix kube controller command line args in 430 branch

- cmd/kube-controller-manager/app/apps.go
- cmd/kube-controller-manager/app/core.go
- hack/arktos-up-scale-out-poc.sh
- pkg/features/kube_features.go
- staging/src/k8s.io/code-generator/_examples/apiserver/openapi/BUILD
- staging/src/k8s.io/sample-apiserver/pkg/generated/openapi/BUILD
Double replicaset & garbage controller QPS. Guarded with feature gates.
> Double GC/RS controller QPS. Guarded with feature gate.

- cmd/haproxy-cfg-generator/cfg_generator.go
- cmd/haproxy-cfg-generator/data/sample_four_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_one_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_three_tp_haproxy.cfg
- cmd/haproxy-cfg-generator/data/sample_two_tp_haproxy.cfg
> /kind bug
Cherry pick fix of bug 1048 from 430 POC branch 
#1048
> bug fix 1048: api server tsl handshake error with proxy server (#1051)

- pkg/controller/volume/scheduling/scheduler_binder.go
__This PR targets POC 430 branch__
/kind feature
This PR is part of multi-RP impl of scale-out arktos; it makes scheduler binder to look node for all RPs, not only the first one.
The code will be exercised with following pvc, storageclass, pod resources:
```
---
piVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: mysc
parameters:
type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: mypvc
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 3Gi
storageClassName: mysc
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
    - name: task-pv-storage …
```
> scheduler binder searches node from all RPs

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/partitionserver-configure-helper.sh
> /kind bug
merge master PR #1058 to POC branch
Fixes #1057 
```release-note
```
> fix rp server failed to collect pprof error (#1058)

- test/kubemark/start-kubemark.sh
hollow-node timeout value is set based on node number and default QPS of 20/sec, plus a buffer time of 15 minutes
Fixes #
```release-note
```
> update hollow-node timeout to 20/sec plus additional 15 minutes

- pkg/scheduler/algorithm/predicates/metadata.go
- pkg/scheduler/algorithm/priorities/interpod_affinity.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/eventhandlers.go
- pkg/scheduler/internal/cache/cache.go
> /kind bug
reduce scheduler log entries by reduce log level for informational log entries.
Fixes #
```release-note
```
> reduce log entries for informational logs

- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
> /kind bug
add missing UT changes in PR 1062
Fixes #
```release-note
```
>  fix UT that missed in PR 1062

- pkg/scheduler/algorithm/predicates/metadata.go
__target to 430 POC branch right now__
> /kind feature (back-port from upstream k8s)
This PR was back-ported from upstream kubernetes [PR 85862]
Partially avoid LabelSelectorAsSelector overhead in anti-pod affinity calculation
Based on the PR author,  schedule 15k pods, this PR improves performance by 18%:
this is the first one of series PRs kube-scheduler related performance related improvements (up to k8s 1.18.5). It will be put out of POC branch until it is perf tested with others in the series. While it is maked as WIP, peer comments are welcome; just not to merge yet.
> kube-sched: perf-related back-ports: Merge pull request #85862 from ahg-g/ahg-antiAffinity

- pkg/version/VERSION.sh
See https://github.com/CentaurusInfra/arktos/pull/985
> Bump Arktos to v0.8.0

- pkg/controller/nodelifecycle/node_lifecycle_controller.go
- pkg/controller/nodelifecycle/scheduler/BUILD
- pkg/controller/nodelifecycle/scheduler/taint_manager.go
- pkg/controller/util/node/controller_utils.go
- staging/src/k8s.io/client-go/tools/cache/mutation_detector.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Pick up performance improvement changes from perf test brancn

- cmd/kubemark/hollow-node.go
/kind bug
It fixes the bug that pods cannot be deleted from hollow-node in perf tests
> bug fix: unable to delete pods at hollow nodes

- cmd/kube-controller-manager/app/core.go
- pkg/controller/nodelifecycle/node_lifecycle_controller.go
- pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
- pkg/controller/util/node/controller_utils.go
- test/integration/scheduler/taint_test.go
This fixed informer index was not added correctly into pod informers of node controller
> Start informer after index was added

- pkg/kubelet/kubelet.go
- pkg/kubelet/kubelet_node_status.go
- pkg/kubelet/kubelet_node_status_test.go
This is Arktos scalability change. Not in community
> Reduce kubelet getting node

- pkg/version/VERSION.sh
> Bump Arktos to v0.9.0

- docs/setup-guide/arktos-with-mizar-cni.md
- hack/arktos-cni.rc
- hack/arktos-up.sh
- hack/lib/common-var-init.sh
- hack/testdata/mizar/deploy.mizar.next.yaml
Minimal changes from PR 1114 + yaml for latest Mizar component deployment
Worked for case 1: VPC0 creation and basic pod connection test in system tenant
Test steps: https://github.com/q131172019/arktos/blob/CarlXie_singleNodeArktosCluster/docs/setup-guide/single-node-dev-scale-up-cluster-with-Mizar.md
> Mizar integration for arktos-up

- cluster/gce/gci/configure-helper-common.sh
> /kind bug
In scaleout, the RP controller will need to run the CSR related ones to get the bootstrap working for Arktos.
```
--controllers=serviceaccount,serviceaccount-token,nodelifecycle,ttl,daemonset,csrsigning,csrapproving,csrcleaner
```
Fixes #
Verified 2tp*2RP kubemark started successfully.
```release-note
```
> Add csr to rp controller

- docs/design-proposals/apiserver/openstack-api-support.md
Initial draft of the openstack api support design spec
> openstack api support design doc

- cluster/gce/util.sh
> /kind bug
Add node tags for rp minion vms to open nodes access ports
Fixes #
```release-note
```
> Add node tags for rp minion vms

- cluster/common.sh
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/configure.sh
- cluster/gce/util.sh
- cluster/get-kube-binaries.sh
>
> /kind bug
> /kind design
/kind feature
> /kind flake
**What this PR does / why we need it**: This is the first step towards getting Mizar deployed and working in Arktos scaleout cluster.
Fixes #
Please review the COS-93 OS changes to see if there's any possibility of regression for current scaleout clusters.
I was able to deploy by calling kube-up.sh with and without NETWORK_PROVIDER=mizar flag.
```release-note
```
> COS-93, Ubuntu 18.04 support with Mizar as static pods in scaleout architecture

- cmd/kube-controller-manager/app/mizarcontrollers.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
* Start arktos network informer
* Grant get/list/update/watch networks permission to mizar arktos network controller
> Bug fix for mizar-arktos network controller watch/update arktos network objects

- cmd/kube-controller-manager/app/controllermanager.go
- hack/arktos-up-scale-out-poc.sh
- hack/arktos-worker-up.sh
Current status:
TP1: ip-172-30-0-14
RP1: ip-172-30-0-41
1. 1TPx1PR scale out cluster running with 3 workers - nodes ready, pods deployment not working yet (due to inconsistent network solution):
```
SCALE_OUT_TP_ENABLE_DAEMONSET=true IS_RESOURCE_PARTITION=false RESOURCE_SERVER=172.30.0.41 TENANT_PARTITION_SERVICE_SUBNET=10.0.0.0/16 ./hack/arktos-up-scale-out-poc.sh -O
IS_RESOURCE_PARTITION=true TENANT_SERVER=172.30.0.14 RESOURCE_PARTITION_POD_CIDR=10.244.0.0/16 ./hack/arktos-up-scale-out-poc.sh -O
IS_SCALE_OUT=true API_HOST=172.30.0.41 API_TENANT_SERVER=172.30.0.14 ./hack/arktos-worker-up.sh
```
2. 1TPx1PR scale out cluster running with 3 workers, with Mizar network - node ready, pod deployment works partially (2nd and later pod on node might hang in network creating). Go to RP node, use …
> Scale out Mizar integration 1x1

- staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackRequestTemplate.json
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
- test/e2e/arktos/testvm.json
UT is just a structure for now to run essential functionalities.
> Use VM name from the request and essential UT for the utility function

- pkg/registry/core/pod/storage/BUILD
- pkg/registry/core/pod/storage/storage.go
- staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
- staging/src/k8s.io/apiserver/pkg/endpoints/request/context.go
* Use explictly set request context in action creation
* BUILD file change
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Cherry-pick: Use explicitly set request context in action creation (#1254)

- pkg/kubelet/kubelet.go
> Bug fix for kubelet service lister: use different service indexer for different TP

- staging/src/k8s.io/apiserver/pkg/util/openstack/flavors.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/images.go
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackRequestTemplate.json
- staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
- test/e2e/arktos/testvm.json
This is the first part of the VM creation to use the openstack flavors and images.
> openstack essential flavors and images support for VM creations -- part 1

- hack/arktos-worker-up.sh
Start worker for multiple TPs. Example:
CNIPLUGIN=mizar IS_SCALE_OUT=true API_HOST=172.30.0.41 API_TENANT_SERVER=172.30.0.14,172.30.0.156 ./hack/arktos-worker-up.sh
> Support adding workers for multiple TPs.

- cluster/addons/dns/coredns/coredns.yaml.base
- cluster/addons/dns/coredns/coredns.yaml.in
- cluster/addons/dns/coredns/coredns.yaml.sed
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure.sh
- cluster/gce/gci/scaleoutserver-helper.sh
- cmd/kubeadm/app/phases/addons/dns/manifests.go
Add python3 installation to support ubuntu for kube-up.sh. 
**Existing issue for this PR**:
Cluster can be started with PR, but if cni plugin using flannel, several pods failed to start: metrics-server, kubernetes-dashboard, event-exporter, corednns. There will be a follow-up PR to fix this issue.
Fixes #
```release-note
```
> add Ubuntu support for kube-up.sh

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/util.sh
1. scale-out TP server enable Daemonset controller
2. add tenant-server-kubeconfig for rp kubelet
Fixes #
```release-note
```
> kube-up.sh support Daemonset for scale-out

- cmd/kube-controller-manager/app/mizarcontrollers.go
- pkg/controller/mizar/mizar-arktos-network-controller.go
- pkg/controller/mizar/mizar-pod-controller.go
- pkg/controller/mizar/mizar-service-controller.go
- plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
Performance improvement for mizar controllers in KCM. This is a improvement suggestion in https://github.com/CentaurusInfra/arktos/pull/1281
> Share same networkInformerFactory in mizar controllers

- hack/arktos-worker-up.sh
When pod is scheduled to worker, it cannot be started correctly - missing proxy in worker. Starting proxy in worker is aligned with production minion deployment.
> Start proxy in worker

- cmd/arktos-network-controller/app/wellknown_service.go
This fix arktos network controller performance issue described in https://github.com/CentaurusInfra/arktos/issues/1311
Before fix:
```
ubuntu@ip-172-30-0-14:~/go/src/k8s.io/arktos$  cat /tmp/kube-apiserver0.log | grep POST | grep services | grep arktos
I0127 16:52:36.951206    4138 wrap.go:47] POST /api/v1/tenants/system/namespaces/kube-system/services: (3.471347ms) 201 [arktos-network-controller/v0.9.0 (linux/amd64) kubernetes/$Format 127.0.0.1:59192]
I0127 16:52:36.986211    4138 wrap.go:47] POST /api/v1/tenants/system/namespaces/default/services: (3.345558ms) 201 [arktos-network-controller/v0.9.0 (linux/amd64) kubernetes/$Format 127.0.0.1:59192]
I0127 16:52:37.156791    4138 wrap.go:47] POST /api/v1/tenants/system/namespaces/default/services: (9.035043ms) 409 …
```
> In get or create service function, get needs to happen before create.

- cluster/common.sh
- cluster/gce/config-default.sh
- cluster/gce/config-test.sh
- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
/kind bug
this PR removes uses of DISABLE_ADMISSION_PLUGINS from kube-up script.
Fixes #1326
this PR was extracted from PR #1327, so as to make the code focused.
```release-note
NONE
```
> kube-up.sh not use  DISABLE_ADMISSION_PLUGINS env var

- docs/design-proposals/apiserver/openstack-api-support.md
> openstack api support doc

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/manifests/kube-proxy.manifest
/kind bug
It sets --tenant-server-kubeconfig arg pointing to TP masters for kube-proxy at RP nodes.
Fixes #1346 
```release-note
NONE
```
> kube-proxy of rp nodes connecting to tp masters

- pkg/controller/mizar/mizar-service-controller.go
1. Fix create mizar service logic
. Remove invalid DNS Service checking logic.
. Break infinite loop for invalid VPC/subnet
2. Consolidate create and update service logic
> Mizar service controller code simplify and logic fix

- cluster/gce/gci/configure-helper-common.sh
- cluster/gce/util.sh
> /kind bug
Fix issue #1361. Deploy Mizar-operator to all tps after all tp and rp server ready.
Only impact kube-up: scale-out
Fixes #1361 
Test scale-out 1x1 and 2x2, both can get all mizar component start successfully.
```
$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/cluster/kubeconfig.tp-1 get pods -A -o wide | grep mizar
default       mizar-daemon-fclm5                                        1563435164262111223   1/1     Running             0          18m   10.40.0.6   sonyaperf2-021522-rp-1-minion-group-5364   <none>           <none>
default       mizar-daemon-nf56m                                        7334669340671240868   1/1 …
```
> fix issue #1361

- cluster/gce/util.sh
Kube-up.sh: start mizar daemon on tp master
Fixes #
Tested on scale-out 2x2 cluster:
```
$ kubectl --kubeconfig=/home/sonyali/go/src/k8s.io/arktos/cluster/kubeconfig.tp-1 get pods -A -o wide | grep mizar
default       mizar-daemon-6549678cfd-7jnwm                             5601951748627010048   1/1     Running             0          5m7s    10.40.0.2   sonyaperf1-021622-tp-1-master              <none>           <none>
default       mizar-daemon-ghszd                                        8714655989251814540   1/1     Running             0          5m8s    10.40.0.5   sonyaperf1-021622-rp-2-master              <none>           <none> …
```
> kube-up: start mizar daemon on tp master

- hack/arktos-up-scale-out-poc.sh
Tested for service creation and curl
> Remove kube-dns from local env.

- docs/design-proposals/multi-tenancy/multi-tenancy-network-mizar-integration.md
Current design doc only includes the implementation of Mizar cniplug support for pod.
Service support is similar, will be added once integration test was done.
> Design doc for Mizar-Arktos Integration
